(()=>{'use strict';
  const params=new URLSearchParams(location.search),kind=['horse','dog','cat'].includes(params.get('univers'))?params.get('univers'):'dog';
  const $=id=>document.getElementById(id),t=(fr,en)=>lang==='en'?en:fr;
  const db=window.supabase?.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  let lang=localStorage.getItem('dicopetsLanguage')==='en'?'en':'fr';
  const breed=(name,size,weight,frTemper,enTemper,frNeeds,enNeeds,budget,frActivity,enActivity)=>({name,size,weight,frTemper,enTemper,frNeeds,enNeeds,budget,frActivity,enActivity});
  const horseBreeds=[
    breed('Connemara','128–148 cm','350–450 kg','Franc, sportif et polyvalent','Honest, athletic and versatile','Vie au pré, contacts sociaux et suivi des pieds','Turnout, social contact and hoof care','3 500–8 000 $ / an','Modérée','Moderate'),
    breed('Haflinger','138–150 cm','400–550 kg','Volontaire, familial et robuste','Willing, family-friendly and sturdy','Ration surveillée et exercice régulier','Careful diet and regular exercise','3 500–8 000 $ / an','Modérée','Moderate'),
    breed('Frison','155–170 cm','600–750 kg','Expressif, généreux et sensible','Expressive, generous and sensitive','Toilettage des fanons et suivi adapté','Feather care and appropriate monitoring','5 000–10 000 $ / an','Modérée','Moderate'),
    breed('Quarter Horse','145–165 cm','430–550 kg','Calme, maniable et polyvalent','Calm, handy and versatile','Travail régulier et environnement stable','Regular work and a stable environment','4 000–9 000 $ / an','Modérée','Moderate'),
    breed('Selle français','155–175 cm','500–650 kg','Sportif, généreux et énergique','Athletic, generous and energetic','Entraînement progressif et suivi sportif','Progressive training and sport monitoring','5 000–10 000 $ / an','Élevée','High'),
    breed('Pur-sang arabe','145–160 cm','350–500 kg','Endurant, vif et proche de l’humain','Enduring, alert and people-oriented','Sorties variées, alimentation adaptée et tact','Varied outings, appropriate diet and tact','4 000–9 000 $ / an','Élevée','High'),
    breed('Appaloosa','142–163 cm','430–550 kg','Curieux, polyvalent et souvent calme','Curious, versatile and often calm','Activité régulière et environnement cohérent','Regular activity and consistent environment','4 000–9 000 $ / an','Modérée','Moderate'),
    breed('Irish Cob','135–160 cm','450–650 kg','Doux, solide et placide','Gentle, sturdy and steady','Surveillance du poids et des fanons','Weight and feather care','4 000–9 000 $ / an','Faible à modérée','Low to moderate'),
    breed('Fjord','135–150 cm','400–500 kg','Sûr, rustique et volontaire','Reliable, hardy and willing','Ration contrôlée et travail régulier','Controlled diet and regular work','3 500–8 000 $ / an','Modérée','Moderate'),
    breed('Islandais','125–145 cm','330–400 kg','Robuste, curieux et endurant','Hardy, curious and enduring','Vie extérieure, groupe et suivi du poids','Outdoor life, herd company and weight care','3 500–8 000 $ / an','Modérée','Moderate'),
    breed('Mérens','145–155 cm','450–550 kg','Calme, sûr et rustique','Calm, sure-footed and hardy','Vie au pré et exercice pour éviter l’embonpoint','Turnout and exercise to prevent weight gain','3 500–8 000 $ / an','Modérée','Moderate'),
    breed('Camargue','135–150 cm','350–450 kg','Résistant, vif et sobre','Resilient, lively and easy-keeping','Vie extérieure et soins adaptés au climat','Outdoor life and climate-appropriate care','3 500–8 000 $ / an','Modérée','Moderate'),
    breed('Lusitanien','155–170 cm','500–600 kg','Sensible, généreux et intelligent','Sensitive, generous and intelligent','Travail régulier, cadre doux et encadrement','Regular work, gentle handling and guidance','5 000–10 000 $ / an','Élevée','High'),
    breed('Andalou','155–170 cm','450–550 kg','Fier, expressif et volontaire','Proud, expressive and willing','Éducation régulière et soins du poil','Regular education and coat care','5 000–10 000 $ / an','Modérée','Moderate'),
    breed('Percheron','160–180 cm','700–1 000 kg','Calme, puissant et gentil','Calm, powerful and gentle','Budget alimentaire, ferrure et place adaptée','Food budget, hoof care and suitable space','6 000–12 000 $ / an','Faible à modérée','Low to moderate'),
    breed('Poney Shetland','90–107 cm','180–250 kg','Malin, robuste et affirmé','Clever, hardy and assertive','Ration très contrôlée et clôtures sûres','Very controlled diet and secure fencing','2 500–6 000 $ / an','Faible à modérée','Low to moderate')
  ];
  const dogBreeds=[
    breed('Welsh Corgi Pembroke','25–30 cm','9–14 kg','Vif, affectueux et intelligent','Lively, affectionate and intelligent','Promenades, jeux de flair et gestion du poids','Walks, scent games and weight management','1 800–4 000 $ / an','Élevée','High'),
    breed('Welsh Corgi Cardigan','26–32 cm','11–17 kg','Loyal, robuste et observateur','Loyal, sturdy and observant','Activité, éducation et soins du dos','Activity, training and back care','1 800–4 000 $ / an','Élevée','High'),
    breed('Bichon maltais','20–25 cm','3–4 kg','Tendre, vif et proche des siens','Tender, lively and close to family','Compagnie quotidienne et entretien du poil','Daily company and coat care','1 500–3 500 $ / an','Faible à modérée','Low to moderate'),
    breed('Bichon frisé','23–30 cm','5–8 kg','Joyeux, sociable et joueur','Cheerful, social and playful','Toilettage régulier et présence','Regular grooming and companionship','1 600–3 600 $ / an','Modérée','Moderate'),
    breed('Labrador Retriever','54–62 cm','25–36 kg','Amical, enthousiaste et éducable','Friendly, enthusiastic and trainable','Activité quotidienne, jeux et contrôle du poids','Daily activity, games and weight management','2 000–4 500 $ / an','Élevée','High'),
    breed('Golden Retriever','51–61 cm','25–34 kg','Doux, coopératif et affectueux','Gentle, cooperative and affectionate','Sorties, brossage et présence familiale','Outings, brushing and family time','2 000–4 500 $ / an','Élevée','High'),
    breed('Border Collie','46–56 cm','14–22 kg','Très intelligent, intense et sensible','Highly intelligent, intense and sensitive','Vrai travail mental, activité et repos','Real mental work, activity and rest','2 000–4 500 $ / an','Très élevée','Very high'),
    breed('Berger australien','46–58 cm','16–32 kg','Énergique, loyal et sensible','Energetic, loyal and sensitive','Éducation, sorties et stimulation quotidienne','Training, outings and daily stimulation','2 000–4 500 $ / an','Très élevée','Very high'),
    breed('Beagle','33–40 cm','9–14 kg','Joyeux, curieux et guidé par son nez','Cheerful, curious and scent-driven','Jeux de flair, sorties sécurisées et patience','Scent games, secure outings and patience','1 700–3 800 $ / an','Élevée','High'),
    breed('Caniche standard','45–60 cm','18–32 kg','Brillant, sportif et attentif','Bright, athletic and attentive','Toilettage, jeux d’intelligence et activité','Grooming, puzzle games and activity','2 200–5 000 $ / an','Élevée','High'),
    breed('Cavapoo','23–36 cm','5–12 kg','Affectueux, joueur et sociable','Affectionate, playful and social','Brossage, apprentissage et compagnie','Brushing, training and company','1 700–4 000 $ / an','Modérée','Moderate'),
    breed('Cockapoo','25–40 cm','6–14 kg','Joyeux, curieux et énergique','Cheerful, curious and energetic','Toilettage et promenades variées','Grooming and varied walks','1 800–4 200 $ / an','Élevée','High'),
    breed('Cocker anglais','38–43 cm','12–15 kg','Joyeux, actif et affectueux','Merry, active and affectionate','Soins des oreilles, flair et activité','Ear care, scent work and activity','1 800–4 000 $ / an','Élevée','High'),
    breed('Whippet','44–51 cm','9–19 kg','Doux, rapide et calme au foyer','Gentle, fast and calm at home','Courses sécurisées et protection contre le froid','Secure running and cold protection','1 700–3 800 $ / an','Élevée','High'),
    breed('Teckel standard','20–27 cm','7–14 kg','Courageux, tenace et amusant','Brave, tenacious and amusing','Jeux de flair et protection du dos','Scent games and back protection','1 700–3 800 $ / an','Modérée','Moderate'),
    breed('Bouledogue français','24–35 cm','8–14 kg','Joueur, sociable et proche de l’humain','Playful, social and people-oriented','Effort modéré, fraîcheur et suivi de santé','Moderate exertion, cool weather and health care','2 000–5 000 $ / an','Faible à modérée','Low to moderate'),
    breed('Shiba Inu','35–43 cm','7–11 kg','Indépendant, vif et réservé','Independent, lively and reserved','Sorties sécurisées, socialisation et patience','Secure outings, socialization and patience','1 800–4 000 $ / an','Élevée','High'),
    breed('Samoyède','48–60 cm','16–30 kg','Sociable, endurant et expressif','Social, enduring and expressive','Activité par temps frais et brossage important','Cool-weather activity and heavy brushing','2 200–5 000 $ / an','Élevée','High')
  ];
  const catBreeds=[
    breed('Maine Coon','25–40 cm','4–10 kg','Sociable, joueur et imposant','Social, playful and large','Hauteur, brossage et matériel robuste','Climbing, brushing and sturdy equipment','1 800–4 000 $ / an','Modérée','Moderate'),
    breed('Ragdoll','23–28 cm','4–9 kg','Doux, sociable et posé','Gentle, social and relaxed','Vie intérieure enrichie et présence','Enriched indoor life and companionship','1 200–3 000 $ / an','Modérée','Moderate'),
    breed('Bengal','22–28 cm','3–7 kg','Athlétique, curieux et intense','Athletic, curious and intense','Jeux, hauteur et interactions fréquentes','Games, climbing and frequent interaction','1 500–3 500 $ / an','Élevée','High'),
    breed('British Shorthair','28–33 cm','4–8 kg','Calme, stable et indépendant','Calm, steady and independent','Jeu modéré et contrôle du poids','Moderate play and weight care','1 200–3 000 $ / an','Faible à modérée','Low to moderate'),
    breed('Siamois','20–25 cm','3–6 kg','Communicatif, curieux et proche des humains','Communicative, curious and people-oriented','Présence, jeu et stimulation quotidienne','Company, play and daily stimulation','1 300–3 200 $ / an','Élevée','High'),
    breed('Sphynx','20–25 cm','3–5 kg','Sociable, drôle et très proche','Social, funny and very affectionate','Chaleur, nettoyage de la peau et présence','Warmth, skin care and company','1 500–3 800 $ / an','Élevée','High'),
    breed('Persan','20–25 cm','3–6 kg','Paisible, doux et discret','Peaceful, gentle and quiet','Brossage quotidien et soins des yeux','Daily brushing and eye care','1 500–3 800 $ / an','Faible','Low'),
    breed('Abyssin','20–25 cm','3–5 kg','Curieux, agile et très joueur','Curious, agile and very playful','Parcours en hauteur et jeux fréquents','Climbing routes and frequent play','1 300–3 200 $ / an','Très élevée','Very high'),
    breed('Sacré de Birmanie','20–25 cm','4–7 kg','Doux, patient et affectueux','Gentle, patient and affectionate','Brossage et compagnie régulière','Brushing and regular company','1 300–3 200 $ / an','Modérée','Moderate'),
    breed('Bleu russe','20–25 cm','3–6 kg','Calme, fidèle et réservé','Calm, loyal and reserved','Routine stable, cachettes et douceur','Stable routine, hiding places and gentle handling','1 200–3 000 $ / an','Modérée','Moderate'),
    breed('Norvégien','25–40 cm','4–9 kg','Agile, sociable et rustique','Agile, social and hardy','Arbre à chat solide et brossage','Sturdy cat tree and brushing','1 500–3 600 $ / an','Élevée','High'),
    breed('Sibérien','25–40 cm','4–9 kg','Joueur, robuste et sociable','Playful, hardy and social','Hauteur, jeu et entretien du poil','Climbing, play and coat care','1 500–3 600 $ / an','Élevée','High'),
    breed('Chartreux','20–25 cm','3–7 kg','Paisible, loyal et discret','Peaceful, loyal and quiet','Jeu quotidien et alimentation mesurée','Daily play and measured feeding','1 200–3 000 $ / an','Modérée','Moderate'),
    breed('Devon Rex','18–25 cm','2,5–4,5 kg','Espiègle, sociable et câlin','Mischievous, social and cuddly','Chaleur, jeux et soins délicats','Warmth, play and gentle care','1 300–3 200 $ / an','Élevée','High'),
    breed('Cornish Rex','18–25 cm','2,5–4,5 kg','Énergique, affectueux et athlétique','Energetic, affectionate and athletic','Maison chaude et nombreuses activités','Warm home and plenty of activity','1 300–3 200 $ / an','Très élevée','Very high'),
    breed('Angora turc','20–30 cm','3–5 kg','Élégant, joueur et affirmé','Elegant, playful and confident','Hauteur, jeu et respect de son autonomie','Climbing, play and respect for independence','1 300–3 300 $ / an','Élevée','High'),
    breed('Bombay','20–25 cm','3–6 kg','Affectueux, curieux et adaptable','Affectionate, curious and adaptable','Compagnie et jeu quotidien','Company and daily play','1 200–3 000 $ / an','Modérée','Moderate'),
    breed('Burmese','20–25 cm','3–6 kg','Très humain, joueur et confiant','Very people-oriented, playful and confident','Présence fréquente et activités partagées','Frequent company and shared activities','1 300–3 200 $ / an','Élevée','High')
  ];
  const worlds={horse:{brand:'DicoCheval',back:'dicocheval.html',breeds:horseBreeds},dog:{brand:'DicoChien',back:'dicochien.html',breeds:dogBreeds},cat:{brand:'DicoChat',back:'dicochat.html',breeds:catBreeds}};
  const world=worlds[kind];
  const copy={horse:{fr:['Mieux choisir et mieux comprendre son cheval','Compare des races, prépare l’arrivée d’un cheval et apprends à observer ses signaux.','Comparer deux races équines','Les informations sont indicatives : l’âge, la santé, l’éducation et l’individu comptent toujours.','Avant d’accueillir un cheval','Cette fiche parle de pension ou d’installations équestres — pas de logement humain.','Comprendre les signaux du cheval','Observe toujours le cheval dans son ensemble et demande conseil à un professionnel en cas de doute.'],en:['Choose and understand your horse','Compare breeds, prepare for a horse and learn to observe its signals.','Compare two horse breeds','Information is indicative: age, health, training and the individual always matter.','Before welcoming a horse','This guide covers boarding or equestrian facilities — not human housing.','Understanding horse signals','Always observe the whole horse and ask a professional when unsure.']},dog:{fr:['Mieux choisir et mieux comprendre son chien','Compare des races, prépare une adoption et apprends à lire les signaux de ton chien.','Comparer deux races de chiens','Les besoins varient avec l’âge, la santé et l’individu.','Avant d’adopter un chien','Ton rythme de vie et tes possibilités d’organisation comptent autant que la race.','Comprendre les signaux du chien','Les signaux sont des indices : respecte toujours la distance et le confort du chien.'],en:['Choose and understand your dog','Compare breeds, prepare for adoption and learn to read your dog’s signals.','Compare two dog breeds','Needs vary with age, health and each individual.','Before adopting a dog','Your daily routine and practical arrangements matter as much as breed.','Understanding dog signals','Signals are clues: always respect a dog’s space and comfort.']},cat:{fr:['Mieux choisir et mieux comprendre son chat','Compare des races, prépare une adoption et apprends à reconnaître les signaux de ton chat.','Comparer deux races de chats','La personnalité dépend aussi du vécu et de l’environnement.','Avant d’accueillir un chat','Prépare un espace sûr, du temps et un budget pour toute sa vie.','Comprendre les signaux du chat','Un chat choisit souvent la distance qui le rassure : laisse-lui cette possibilité.'],en:['Choose and understand your cat','Compare breeds, prepare for adoption and learn to recognize your cat’s signals.','Compare two cat breeds','Personality also depends on life history and environment.','Before welcoming a cat','Prepare a safe space, time and a lifelong budget.','Understanding cat signals','Cats often choose the distance that makes them feel safe: let them do so.']}};
  const labels={horse:{fr:[['Temps pour les visites et soins',['Moins de 3 visites par semaine','4 à 6 visites par semaine','Tous les jours ou presque']],['Hébergement prévu',['Pension complète en écurie','Pension avec soins partagés','Propriété avec installations adaptées']],['Encadrement prévu',['Cours / professionnel régulier','Cavalier accompagné','Cavalier expérimenté']]],en:[['Time for visits and care',['Less than 3 visits a week','4 to 6 visits a week','Every day or almost every day']],['Planned boarding',['Full-care boarding','Shared-care boarding','Property with suitable facilities']],['Planned guidance',['Regular lessons / professional','Supported rider','Experienced rider']]]},dog:{fr:[['Temps disponible chaque jour',['Moins de 45 minutes','45 à 90 minutes','Plus de 90 minutes']],['Logement et sorties',['Appartement avec sorties','Maison avec sorties','Maison et espace sécurisé']],['Expérience avec les chiens',['Je débute','J’ai déjà de l’expérience','Je suis très expérimenté·e']]],en:[['Daily available time',['Less than 45 minutes','45 to 90 minutes','More than 90 minutes']],['Home and outings',['Apartment with outings','House with outings','House and secure space']],['Dog experience',['I am new','I have experience','I am very experienced']]]},cat:{fr:[['Temps à la maison',['Peu de temps','Présence régulière','Très présent·e']],['Sécurité du milieu de vie',['Intérieur enrichi','Intérieur avec balcon sécurisé','Accès extérieur réellement sécurisé']],['Autres animaux à la maison',['Aucun autre animal','Animal calme déjà présent','Plusieurs animaux']]],en:[['Time at home',['Little time','Regular presence','Very present']],['Safety of the living space',['Enriched indoor home','Indoor home with secure balcony','Truly secure outdoor access']],['Other animals at home',['No other animals','One calm resident animal','Several animals']]]}};
  function option(value,label){return `<option value="${value}">${label}</option>`}
  function profile(b){return `<article class="profile"><h3>${b.name}</h3><dl><div><dt>${t('Taille','Height')}</dt><dd>${b.size}</dd></div><div><dt>${t('Poids','Weight')}</dt><dd>${b.weight}</dd></div><div><dt>${t('Caractère','Temperament')}</dt><dd>${t(b.frTemper,b.enTemper)}</dd></div><div><dt>${t('Besoins','Needs')}</dt><dd>${t(b.frNeeds,b.enNeeds)}</dd></div><div><dt>${t('Budget annuel indicatif','Estimated annual budget')}</dt><dd>${b.budget}</dd></div><div><dt>${t('Activité','Activity')}</dt><dd>${t(b.frActivity,b.enActivity)}</dd></div></dl></article>`}
  function selected(select){return Number(select.value)}
  function ensureDifferent(changed){const first=$('firstBreed'),second=$('secondBreed');if(selected(first)!==selected(second))return;if(changed===first)second.value=String((selected(first)+1)%world.breeds.length);else first.value=String((selected(second)+world.breeds.length-1)%world.breeds.length)}
  function renderComparison(){ensureDifferent(null);$('comparison').innerHTML=profile(world.breeds[selected($('firstBreed'))])+profile(world.breeds[selected($('secondBreed'))])}
  function renderSelects(){const previous=[selected($('firstBreed')),selected($('secondBreed'))];[$('firstBreed'),$('secondBreed')].forEach((select,index)=>select.innerHTML=world.breeds.map((b,i)=>`<option value="${i}">${b.name}</option>`).join(''));$('firstBreed').value=String(Number.isInteger(previous[0])?previous[0]:0);$('secondBreed').value=String(Number.isInteger(previous[1])&&previous[1]!==selected($('firstBreed'))?previous[1]:1);renderComparison()}
  function renderAdoptionInputs(){const set=labels[kind][lang];[['time',0],['home',1],['experience',2]].forEach(([id,index])=>{$(id+'Label').textContent=set[index][0];$(id).innerHTML=set[index][1].map((label,i)=>option(String(i),label)).join('')})}
  function adoption(){const values=[selected($('time')),selected($('home')),selected($('experience'))];const lines=[];if(kind==='horse'){lines.push(t('Vérifie précisément ce que comprend la pension : fourrage, sorties, surveillance, maréchalerie, transport en urgence et disponibilité des installations.','Check exactly what boarding includes: forage, turnout, monitoring, farrier care, emergency transport and access to facilities.'));if(values[0]===0)lines.push(t('Avec peu de visites, une pension complète fiable et un budget de soins imprévus sont essentiels.','With fewer visits, reliable full-care boarding and an emergency care budget are essential.'));if(values[2]===0)lines.push(t('Prévois des cours, un essai avec un professionnel et l’avis de la personne qui connaît le cheval.','Plan lessons, a trial with a professional and advice from the person who knows the horse.'))}else if(kind==='dog'){lines.push(t('Prévois des sorties quotidiennes, un plan pour les absences, une éducation bienveillante et un budget vétérinaire d’urgence.','Plan daily outings, a plan for absences, kind training and an emergency veterinary budget.'));if(values[0]===0)lines.push(t('Favorise un chien dont les besoins d’activité correspondent réellement à ton temps disponible.','Favour a dog whose activity needs truly match your available time.'));if(values[1]===0)lines.push(t('Un appartement peut convenir : le jardin ne remplace pas les promenades, le repos et les activités.','An apartment can work: a yard does not replace walks, rest and activities.'))}else{lines.push(t('Prévois un vétérinaire, un budget d’urgence, une litière adaptée, des cachettes, des hauteurs et un enrichissement quotidien.','Plan a veterinarian, emergency budget, suitable litter, hiding places, climbing and daily enrichment.'));if(values[2]>0)lines.push(t('Organise des présentations lentes et des ressources séparées pour les animaux déjà présents.','Plan slow introductions and separate resources for animals already present.'));if(values[1]===2)lines.push(t('L’accès extérieur doit être réellement sécurisé : l’extérieur libre comporte des risques importants.','Outdoor access must be genuinely secure: free roaming has important risks.'))}lines.push(t('Rencontre l’animal plusieurs fois et demande son historique de santé et de comportement avant toute décision.','Meet the animal several times and ask for health and behavioural history before any decision.'));$('adoptionResult').innerHTML='<strong>'+t('Ta checklist personnelle','Your personal checklist')+'</strong><ul>'+lines.map(line=>'<li>'+line+'</li>').join('')+'</ul>'}
  function signals(){const all={horse:[['👂','Oreilles','Ears','Oreilles souples : il observe. Oreilles plaquées longtemps : augmente la distance et cherche la cause.','Soft ears: the horse is observing. Ears held back for a long time: give space and look for the cause.'],['↔','Queue','Tail','Une queue agitée peut signaler des insectes ou une tension : regarde tout le corps.','A moving tail can signal insects or tension: check the whole body.'],['◡','Posture','Posture','Un cheval détendu répartit son poids calmement. Une posture figée mérite une attention douce.','A relaxed horse distributes weight calmly. A frozen posture deserves gentle attention.'],['◉','Expression','Expression','Respiration, regard et lèvres donnent des indices : ne conclus jamais avec un seul signe.','Breathing, eyes and lips give clues: never conclude from one signal.']],dog:[['👂','Oreilles','Ears','Oreilles en arrière ou sur le côté peuvent montrer une gêne : donne de l’espace.','Ears back or to the side can show discomfort: give space.'],['↘','Queue','Tail','Une queue basse peut signaler de l’inquiétude; une queue qui bouge n’est pas toujours une invitation.','A low tail may signal worry; a wagging tail is not always an invitation.'],['◒','Posture','Posture','Un corps souple invite souvent au jeu; un corps raide demande du calme et de la distance.','A loose body often invites play; a stiff body asks for calm and distance.'],['◉','Regard','Eyes','Détourner la tête, cligner ou bâiller peut aider à apaiser une situation.','Turning away, blinking or yawning can help soothe a situation.']],cat:[['👂','Oreilles','Ears','Oreilles vers l’avant : intérêt. Oreilles aplaties : laisse le chat tranquille.','Ears forward: interest. Flattened ears: leave the cat alone.'],['〰','Queue','Tail','Une queue qui fouette vite signale souvent de l’agacement : arrête doucement l’interaction.','A quickly lashing tail often signals irritation: gently end the interaction.'],['⌒','Posture','Posture','Un dos rond et des poils hérissés peuvent indiquer de la peur : ne force jamais le contact.','An arched back and raised fur can show fear: never force contact.'],['◉','Clignement lent','Slow blink','Un clignement lent est souvent un signe de détente si le reste du corps est calme.','A slow blink is often a relaxed sign when the rest of the body is calm.']]}[kind];$('signals').innerHTML=all.map(([icon,frTitle,enTitle,frText,enText])=>`<article class="signal"><div class="signal-illustration">${icon}</div><h3>${t(frTitle,enTitle)}</h3><p>${t(frText,enText)}</p></article>`).join('')}
  async function loadFavourites(){const local=JSON.parse(localStorage.getItem('dicopetsFavorites')||'{}'),list=local[kind]||[];$('favouriteStatus').textContent=list.length?t('Favoris actuels : ','Current favourites: ')+list.join(', '):t('Tu peux sauvegarder les deux races comparées dans ton espace membre.','You can save the two compared breeds in your member area.')}
  async function saveFavourites(){const local=JSON.parse(localStorage.getItem('dicopetsFavorites')||'{}'),names=[world.breeds[selected($('firstBreed'))].name,world.breeds[selected($('secondBreed'))].name];local[kind]=[...new Set([...(local[kind]||[]),...names])].slice(0,20);localStorage.setItem('dicopetsFavorites',JSON.stringify(local));if(db){const {data}=await db.auth.getUser();if(data.user)await db.auth.updateUser({data:{favorite_breeds:local}})}loadFavourites()}
  function render(){const c=copy[kind][lang];document.documentElement.lang=lang;$('brand').textContent='DicoPets · '+world.brand;$('back').href=world.back;$('back').textContent=t('← Retour à '+world.brand,'← Back to '+world.brand);$('eyebrow').textContent=t('Guides pratiques','Practical guides');$('title').textContent=c[0];$('intro').textContent=c[1];$('compareTitle').textContent=c[2];$('compareLead').textContent=c[3];$('adoptionTitle').textContent=c[4];$('adoptionLead').textContent=c[5];$('signalsTitle').textContent=c[6];$('signalsLead').textContent=c[7];$('firstLabel').textContent=t('Première race','First breed');$('secondLabel').textContent=t('Deuxième race','Second breed');$('showAdoption').textContent=t('Voir ma fiche avant d’adopter','Show my pre-adoption guide');$('saveFavourite').textContent=t('Sauvegarder les races comparées','Save compared breeds');document.body.dataset.universe=kind;renderSelects();renderAdoptionInputs();signals();adoption();loadFavourites()}
  $('language').value=lang;$('language').addEventListener('change',()=>{lang=$('language').value;localStorage.setItem('dicopetsLanguage',lang);render()});$('firstBreed').addEventListener('change',()=>{ensureDifferent($('firstBreed'));renderComparison()});$('secondBreed').addEventListener('change',()=>{ensureDifferent($('secondBreed'));renderComparison()});$('showAdoption').addEventListener('click',adoption);$('saveFavourite').addEventListener('click',saveFavourites);render();
})();
