/* Recherche commune : rubriques, races connues et profils de membres. */
(() => {
  const input=document.getElementById('dicopetsSearchInput'),box=document.getElementById('dicopetsSearchResults');
  if(!input||!box)return;
  const db=window.supabase?.createClient?.('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  const items=[
    ['DicoCheval','Univers','Races, disciplines, soins, équipement, anatomie et quiz.','dicocheval.html'],
    ['Races équines','DicoCheval','Chevaux, poneys et fiches détaillées.','races.html'],
    ['Mon cheval idéal','DicoCheval','Questionnaire pour comparer des pistes de races.','cheval-ideal.html'],
    ['DicoChien','Univers','Races de chiens, santé, éducation et outils.','dicochien.html'],
    ['Races de chiens','DicoChien','Fiches détaillées des races de chiens.','dicochien.html?section=races'],
    ['Mon chien idéal','DicoChien','Trouver des races compatibles avec ton quotidien.','outils-chien.html?outil=ideal'],
    ['DicoChat','Univers','Races félines, comportement, santé et outils.','dicochat.html'],
    ['Races de chats','DicoChat','Fiches détaillées des races de chats.','dicochat.html#races'],
    ['Mon chat idéal','DicoChat','Trouver des profils de chats compatibles.','outils-chat.html?outil=ideal'],
    ['Actualités','DicoPets','Les nouveautés publiées par la créatrice.','#actualite'],
    ['Crédits photos','DicoPets','Les sources des images utilisées sur la plateforme.','credits.html']
  ];
  const normalise=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const esc=value=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const isEnglish=()=>localStorage.getItem('dicopetsLanguage')==='en';
  document.head.insertAdjacentHTML('beforeend','<style>.dicopets-search{padding:0 0 16px;background:var(--cream)}.dicopets-search-box{display:grid;grid-template-columns:.9fr 1.1fr;gap:28px;align-items:center;padding:26px 30px;border:1px solid var(--line);border-radius:20px;background:var(--paper);box-shadow:0 12px 30px #173b3010}.dicopets-search h2{font-size:clamp(28px,4vw,42px);margin:0}.dicopets-search p{margin:4px 0 0;color:var(--muted)}.dicopets-search-control{position:relative}.dicopets-search-control input{width:100%;padding:15px 17px;border:1px solid #aebfaf;border-radius:999px;background:#fff;color:var(--ink);font:inherit}.dicopets-search-results{display:none;position:absolute;z-index:70;inset:calc(100% + 8px) 0 auto;background:#fffdf8;border:1px solid #cbd8ce;border-radius:14px;box-shadow:0 16px 35px #1735262b;overflow:hidden}.dicopets-search-results.open{display:block}.dicopets-search-result{display:flex;gap:11px;align-items:center;width:100%;padding:12px 14px;background:transparent;border:0;border-bottom:1px solid #e3eae2;color:var(--ink);font:inherit;text-align:left;text-decoration:none;cursor:pointer}.dicopets-search-result:last-child{border-bottom:0}.dicopets-search-result:hover{background:#edf2ea}.dicopets-search-kind{display:inline-block;min-width:72px;color:#9d7133;font-size:11px;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.dicopets-search-result small{display:block;color:var(--muted);margin-top:2px}.dicopets-search-avatar{width:38px;height:38px;object-fit:cover;border-radius:50%;background:#edf2ea}.dicopets-search-empty{padding:14px;color:var(--muted)}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:720px){.dicopets-search-box{grid-template-columns:1fr;padding:22px}.dicopets-search{padding:16px 0 0}}</style>');
  function staticMatches(term){return items.filter(item=>normalise(item.join(' ')).includes(term)).slice(0,6)}
  function staticRow(item){return `<a class="dicopets-search-result" href="${esc(item[3])}"><span class="dicopets-search-kind">${esc(item[1])}</span><span><b>${esc(item[0])}</b><small>${esc(item[2])}</small></span></a>`}
  function memberRow(profile){const favorites=profile.favorites&&typeof profile.favorites==='object'?Object.values(profile.favorites).flat():[];const joined=new Intl.DateTimeFormat(isEnglish()?'en-US':'fr-CA',{year:'numeric',month:'short',day:'numeric'}).format(new Date(profile.membre_depuis));const meta=isEnglish()?`${profile.points||0} points · Member since ${joined}`:`${profile.points||0} points · Membre depuis le ${joined}`;const favoriteText=favorites.length?(isEnglish()?'Favourites: ':'Races favorites : ')+favorites.slice(0,5).join(', '):'';return `<a class="dicopets-search-result" href="membre.html?pseudo=${encodeURIComponent(profile.pseudo)}"><img class="dicopets-search-avatar" src="${esc(profile.avatar_url||'assets/avatar-0.png')}" alt=""><span class="dicopets-search-kind">${isEnglish()?'Member':'Membre'}</span><span><b>${esc(profile.pseudo)}</b><small>${esc(meta)}${favoriteText?' · '+esc(favoriteText):''}</small></span></a>`}
  async function find(){const term=normalise(input.value.trim());box.classList.remove('open');box.innerHTML='';if(!term)return;const staticHtml=staticMatches(term).map(staticRow).join('');let memberHtml='';if(db){let {data,error}=await db.from('profils_publics').select('pseudo,avatar_url,points,membre_depuis,favorites').ilike('pseudo',input.value.trim().replace(/[%_]/g,'')+'%').order('points',{ascending:false}).limit(6);if(error)({data}=await db.from('profils_publics').select('pseudo,avatar_url,points,membre_depuis').ilike('pseudo',input.value.trim().replace(/[%_]/g,'')+'%').order('points',{ascending:false}).limit(6));data=(data||[]).filter(profile=>normalise(profile.pseudo).replace(/\s/g,'')!=='dicocheval');memberHtml=data.map(memberRow).join('')}const html=memberHtml+staticHtml;box.innerHTML=html||`<div class="dicopets-search-empty">${isEnglish()?'No result found.':'Aucun résultat trouvé.'}</div>`;box.classList.add('open')}
  let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(find,180)});input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();find()}});document.addEventListener('click',event=>{if(!event.target.closest('.dicopets-search-control'))box.classList.remove('open')});
})();
