(() => {
  const B = (fr,en,size,activity,height,weight,traitsFr,traitsEn,dailyFr,dailyEn,characterFr,characterEn,qualitiesFr,qualitiesEn,knowFr,knowEn) => ({fr,en,size,activity,height,weight,traitsFr,traitsEn,dailyFr,dailyEn,characterFr,characterEn,qualitiesFr,qualitiesEn,knowFr,knowEn});
  const breeds = [
    B('Basset Hound','Basset Hound','medium','moderate','28–38 cm','20–34 kg','Calme, affectueux, persévérant et guidé par son flair.','Calm, affectionate, persistent and scent-driven.','45 à 75 min de marche tranquille et jeux de flair, sans excès de sauts.','45–75 min of steady walking and scent games, without excessive jumping.','Chien courant français au corps long, sociable mais parfois très têtu lorsqu’une odeur l’intéresse.','French scent hound with a long body, sociable but often stubborn when following a scent.',['Doux','Excellent flair','Patient'],['Gentle','Excellent nose','Patient'],'Surveiller le poids, les oreilles, la peau et le dos; les escaliers répétés peuvent être difficiles.','Watch weight, ears, skin and back; repeated stairs may be difficult.'),
    B('Bichon frisé','Bichon Frise','small','moderate','23–30 cm','5–8 kg','Joyeux, sociable, joueur et peu sujet à la mue.','Cheerful, sociable, playful and low-shedding.','45 à 60 min de sorties, jeux et contacts quotidiens.','45–60 min of outings, play and daily companionship.','Petit compagnon blanc et bouclé, adaptable et souvent très proche de sa famille.','Small white curly companion, adaptable and often very close to family.',['Joyeux','Adaptable','Sociable'],['Cheerful','Adaptable','Sociable'],'Le poil frisé exige brossage et toilettage professionnel régulier.','The curly coat requires brushing and regular professional grooming.'),
    B('Bichon maltais','Maltese','small','moderate','20–25 cm','3–4 kg','Tendre, vif, élégant et très attaché à ses humains.','Tender, lively, elegant and strongly attached to people.','30 à 60 min en petites promenades et jeux doux.','30–60 min in short walks and gentle play.','Très petit chien de compagnie au long poil blanc, alerte malgré son apparence délicate.','Very small white long-coated companion, alert despite its delicate appearance.',['Affectueux','Vif','Peu de mue'],['Affectionate','Lively','Low-shedding'],'Entretien fréquent du poil, des yeux et des dents; manipulations délicates nécessaires.','Frequent coat, eye and dental care; gentle handling is required.'),
    B('Cavapoo','Cavapoo','small','moderate','23–36 cm','5–12 kg','Affectueux, sociable et généralement joueur.','Affectionate, social and generally playful.','45 à 75 min de promenades, jeux et apprentissages.','45–75 min of walks, play and training.','Croisement entre Cavalier King Charles Spaniel et Caniche; taille, poil et caractère peuvent beaucoup varier.','Cross between a Cavalier King Charles Spaniel and Poodle; size, coat and temperament can vary widely.',['Affectueux','Sociable','Éducable'],['Affectionate','Sociable','Trainable'],'Ce croisement n’a pas un standard unique. Vérifier la santé des deux lignées parentales et prévoir un toilettage régulier.','This cross has no single standard. Check both parent lines for health and expect regular grooming.'),
    B('Cockapoo','Cockapoo','medium','high','25–40 cm','6–14 kg','Joyeux, affectueux, curieux et énergique.','Cheerful, affectionate, curious and energetic.','60 à 90 min de promenades, flair, jeux et apprentissages.','60–90 min of walks, scent work, play and training.','Croisement entre Cocker et Caniche dont le format et le pelage varient selon les parents.','Cocker-Poodle cross whose size and coat vary according to the parents.',['Joyeux','Proche des humains','Polyvalent'],['Cheerful','People-oriented','Versatile'],'Le toilettage peut être exigeant et il faut vérifier la santé des deux lignées parentales.','Grooming can be demanding and both parent lines require health screening.'),
    B('Épagneul nain continental Papillon','Papillon','small','high','20–28 cm','2,5–5 kg','Brillant, vif, élégant et étonnamment sportif.','Bright, lively, elegant and surprisingly athletic.','45 à 75 min de promenades, jeux et apprentissages variés.','45–75 min of walks, play and varied training.','Petit épagneul européen aux oreilles frangées, très réceptif et souvent excellent en sports canins.','Small European spaniel with fringed ears, highly responsive and often excellent in dog sports.',['Intelligent','Agile','Joyeux'],['Intelligent','Agile','Cheerful'],'Sa petite taille demande des interactions surveillées avec les jeunes enfants.','Its small size requires supervised interactions with young children.'),
    B('Samoyède','Samoyed','large','high','48–60 cm','16–30 kg','Sociable, expressif, endurant et très fourni en poil.','Sociable, expressive, enduring and heavily coated.','90 à 120 min avec marche, traction légère ou jeux par temps frais.','90–120 min of walking, light pulling or play in cool weather.','Spitz nordique blanc historiquement utilisé pour le travail et la vie auprès des familles.','White northern spitz historically used for work and close family life.',['Sociable','Endurant','Joyeux'],['Sociable','Enduring','Cheerful'],'Mue très importante, chaleur difficile et tendance à vocaliser ou creuser.','Very heavy shedding, poor heat tolerance and a tendency to vocalize or dig.'),
    B('Schnauzer nain','Miniature Schnauzer','small','high','30–36 cm','5–9 kg','Alerte, intelligent, robuste et plein de personnalité.','Alert, intelligent, sturdy and full of personality.','60 à 90 min de sorties, flair et apprentissages.','60–90 min of outings, scent work and training.','Petit chien allemand à poil dur, vigilant et généralement très proche de sa famille.','Small wire-coated German dog, vigilant and generally close to family.',['Robuste','Intelligent','Alerte'],['Sturdy','Intelligent','Alert'],'Toilettage régulier et gestion des aboiements; surveiller le poids et la santé métabolique.','Regular grooming and barking management; watch weight and metabolic health.'),
    B('Shiba Inu','Shiba Inu','medium','high','35–43 cm','7–11 kg','Indépendant, propre, vif et réservé.','Independent, clean, lively and reserved.','60 à 90 min de promenades et exploration en sécurité.','60–90 min of walks and secure exploration.','Spitz japonais autonome, expressif et souvent peu intéressé par une obéissance répétitive.','Independent Japanese spitz, expressive and often uninterested in repetitive obedience.',['Propre','Agile','Digne'],['Clean','Agile','Dignified'],'Rappel prudent, instinct de chasse et socialisation réfléchie; peu recommandé comme premier chien.','Cautious recall, prey drive and thoughtful socialization; not ideal as a first dog.'),
    B('Welsh Corgi Cardigan','Cardigan Welsh Corgi','small','high','26–32 cm','11–17 kg','Loyal, intelligent, solide et un peu réservé.','Loyal, intelligent, sturdy and somewhat reserved.','60 à 90 min de promenades, flair et apprentissages.','60–90 min of walking, scent games and training.','Ancien berger gallois à longue queue, plus lourd et distinct du Corgi Pembroke.','Ancient long-tailed Welsh herder, heavier and distinct from the Pembroke Corgi.',['Loyal','Polyvalent','Robuste'],['Loyal','Versatile','Sturdy'],'Surveiller le poids et le dos; il peut être vocal et vouloir rassembler ce qui bouge.','Watch weight and back; it may be vocal and try to herd moving things.'),
    B('Whippet','Whippet','medium','high','44–51 cm','9–19 kg','Doux, rapide, discret et calme à la maison.','Gentle, fast, quiet and calm at home.','60 à 90 min avec promenades et courses libres dans un espace entièrement sécurisé.','60–90 min with walks and free running in a fully secure area.','Lévrier britannique athlétique dehors mais souvent très posé et sensible à l’intérieur.','British sighthound athletic outdoors but often calm and sensitive indoors.',['Doux','Rapide','Calme au foyer'],['Gentle','Fast','Calm at home'],'Fort instinct de poursuite, sensibilité au froid et besoin d’un espace sécurisé pour courir.','Strong chase instinct, cold sensitivity and need for a secure running area.'),
    B('Welsh Corgi Pembroke','Pembroke Welsh Corgi','small','high','25–30 cm','9–14 kg','Vif, affectueux, intelligent et plein d’assurance.','Lively, affectionate, intelligent and self-assured.','60 à 90 min de promenades, jeux de flair et apprentissages; surveiller les sauts répétés.','60–90 min of walks, scent games and training; limit repeated jumping.','Petit chien de berger gallois, bas sur pattes mais énergique, sociable et très attentif à sa famille.','Low-set Welsh herding dog that is energetic, social and very attentive to family.',['Joyeux','Intelligent','Polyvalent'],['Cheerful','Intelligent','Versatile'],'Sa morphologie demande une attention au poids et au dos. Il peut être vocal et tenter de rassembler les personnes.','Its build requires careful weight and back management. It may be vocal and try to herd people.'),
    B('Labrador Retriever','Labrador Retriever','large','high','54–62 cm','25–36 kg','Sociable, enthousiaste et proche de sa famille.','Social, enthusiastic and family-oriented.','Environ 90 à 120 min d’activité, jeux de rapport et stimulation mentale.','About 90–120 min of activity, retrieving games and mental stimulation.','Chien de rapport puissant, gourmand, joueur et généralement facile à motiver.','Powerful retrieving dog; food-motivated, playful and usually easy to engage.',['Amical','Polyvalent','Éducable'],['Friendly','Versatile','Trainable'],'Surveiller le poids; il supporte mal l’ennui et a besoin d’interactions quotidiennes.','Watch weight; this breed handles boredom poorly and needs daily interaction.'),
    B('Golden Retriever','Golden Retriever','large','high','51–61 cm','25–34 kg','Doux, coopératif et très attaché aux humains.','Gentle, cooperative and strongly people-oriented.','90 à 120 min, jeux, nage possible et exercices d’éducation.','90–120 min, games, optional swimming and training exercises.','Retriever sensible et volontaire, souvent à l’aise en famille et dans les activités assistées.','Sensitive, willing retriever often comfortable in families and assistance work.',['Patient','Affectueux','Fiable'],['Patient','Affectionate','Reliable'],'Mue importante et toilettage régulier; choisir un élevage attentif à la santé.','Heavy shedding and regular grooming; choose a health-conscious breeder.'),
    B('Berger allemand','German Shepherd Dog','large','very-high','55–65 cm','22–40 kg','Loyal, vigilant, intelligent et très engagé dans le travail.','Loyal, alert, intelligent and highly work-oriented.','90 à 120 min ou plus, avec obéissance, flair et vraies tâches mentales.','90–120 min or more, including obedience, scent work and meaningful mental tasks.','Berger athlétique et protecteur qui apprend vite et demande une socialisation soignée.','Athletic, protective herder that learns quickly and needs thoughtful socialization.',['Loyal','Courageux','Travailleur'],['Loyal','Brave','Hard-working'],'Demande du temps, une éducation cohérente et un dépistage sérieux des hanches et coudes.','Needs time, consistent training and responsible hip and elbow screening.'),
    B('Caniche standard','Standard Poodle','large','high','45–60 cm','18–32 kg','Brillant, sportif, attentif et peu sujet à la mue.','Bright, athletic, attentive and low-shedding.','60 à 120 min, jeux d’intelligence, rapport et apprentissages variés.','60–120 min, puzzle games, retrieving and varied training.','Chien d’eau élégant, très adaptable, dont le poil pousse continuellement.','Elegant, highly adaptable water dog with continuously growing hair.',['Très intelligent','Polyvalent','Attentif'],['Highly intelligent','Versatile','Attentive'],'Le toilettage professionnel et le brossage représentent un vrai budget de temps et d’argent.','Professional grooming and brushing require significant time and money.'),
    B('Bouledogue français','French Bulldog','small','moderate','24–35 cm','8–14 kg','Joueur, affectueux, comique et très proche de ses humains.','Playful, affectionate, amusing and very people-oriented.','30 à 60 min en plusieurs sorties calmes; éviter chaleur et effort intense.','30–60 min split into calm outings; avoid heat and intense exertion.','Petit molosse brachycéphale, compact, sociable et adapté à une vie moins sportive.','Compact, social brachycephalic companion suited to a less athletic lifestyle.',['Affectueux','Adaptable','Enjoué'],['Affectionate','Adaptable','Playful'],'La respiration et la chaleur sont des enjeux majeurs; consulter un vétérinaire avant un programme d’exercice.','Breathing and heat are major concerns; consult a vet before an exercise program.'),
    B('Beagle','Beagle','medium','high','33–40 cm','9–14 kg','Joyeux, curieux, gourmand et guidé par son nez.','Cheerful, curious, food-motivated and led by its nose.','60 à 90 min, longues promenades en laisse et jeux de flair.','60–90 min, long leash walks and scent games.','Petit chien courant sociable, endurant et parfois vocal ou indépendant.','Sociable, enduring small scent hound that can be vocal and independent.',['Sociable','Robuste','Joyeux'],['Sociable','Sturdy','Cheerful'],'Le rappel peut être difficile; sécuriser les espaces et occuper son odorat.','Recall can be difficult; use secure areas and engage the nose.'),
    B('Border Collie','Border Collie','medium','very-high','46–56 cm','14–22 kg','Extrêmement réactif, intelligent et concentré sur le mouvement.','Extremely responsive, intelligent and movement-focused.','Au moins 120 min combinant activité physique, troupeau, flair ou apprentissage.','At least 120 min combining physical activity, herding, scent work or training.','Berger d’exception qui a davantage besoin d’un travail réfléchi que de courir sans but.','Exceptional herder needing thoughtful work more than aimless running.',['Brillant','Précis','Endurant'],['Brilliant','Precise','Enduring'],'Peut développer des comportements compulsifs s’il manque de repos, d’encadrement ou de stimulation adaptée.','Can develop compulsive behavior without rest, guidance or suitable stimulation.'),
    B('Berger australien','Australian Shepherd','medium','very-high','46–58 cm','16–32 kg','Énergique, fidèle, sensible et naturellement rassembleur.','Energetic, loyal, sensitive and naturally inclined to herd.','90 à 120 min avec éducation, jeux contrôlés et activité canine.','90–120 min with training, controlled play and canine activities.','Berger athlétique qui aime participer à tout et peut se montrer réservé avec les inconnus.','Athletic herder that wants to join every activity and may be reserved with strangers.',['Polyvalent','Loyal','Enthousiaste'],['Versatile','Loyal','Enthusiastic'],'Il ne devient pas calme simplement grâce à un jardin; il lui faut apprentissage et temps de repos.','A yard alone will not make this dog calm; training and rest are essential.'),
    B('Husky sibérien','Siberian Husky','medium','very-high','50–60 cm','16–27 kg','Endurant, sociable, indépendant et amateur de course.','Enduring, social, independent and built to run.','120 min ou plus, idéalement traction ou course sécurisée par temps frais.','120 min or more, ideally pulling or secure running in cool weather.','Chien nordique de meute, vocal, autonome et doté d’un fort instinct d’exploration.','Vocal, independent northern pack dog with a strong urge to explore.',['Endurant','Sociable','Joueur'],['Enduring','Sociable','Playful'],'Clôture solide, rappel prudent, grosse mue et adaptation des sorties à la chaleur.','Secure fencing, cautious recall, heavy shedding and heat-aware exercise are essential.'),
    B('Chihuahua','Chihuahua','small','moderate','15–23 cm','1,5–3 kg','Vif, loyal, expressif et beaucoup plus audacieux que sa taille.','Lively, loyal, expressive and far bolder than its size.','30 à 60 min en petites sorties, jeux et apprentissages doux.','30–60 min in short outings, play and gentle training.','Très petit chien de compagnie, alerte et sensible au froid.','Very small, alert companion dog sensitive to cold.',['Loyal','Vif','Transportable'],['Loyal','Lively','Portable'],'Sa fragilité physique exige des manipulations délicates et des interactions surveillées avec les enfants.','Physical fragility requires gentle handling and supervised interactions with children.'),
    B('Yorkshire Terrier','Yorkshire Terrier','small','moderate','18–23 cm','2–3,2 kg','Vif, confiant, affectueux et doté d’un vrai tempérament de terrier.','Lively, confident, affectionate and truly terrier-like.','30 à 60 min, jeux, promenades et courte stimulation mentale.','30–60 min of games, walks and short mental challenges.','Petit terrier de compagnie au poil fin qui ne doit pas être traité comme un jouet.','Small fine-coated companion terrier that should not be treated like a toy.',['Courageux','Alerte','Affectueux'],['Brave','Alert','Affectionate'],'Brossage fréquent et attention aux dents, aux genoux et aux chutes.','Frequent brushing and attention to teeth, knees and falls.'),
    B('Cavalier King Charles Spaniel','Cavalier King Charles Spaniel','small','moderate','30–33 cm','5,4–8,2 kg','Tendre, sociable, doux et heureux près de sa famille.','Tender, social, gentle and happiest near family.','45 à 60 min, promenades tranquilles et jeux relationnels.','45–60 min of relaxed walks and interactive play.','Épagneul de compagnie adaptable, rarement heureux lorsqu’il reste seul longtemps.','Adaptable companion spaniel rarely happy when left alone for long periods.',['Doux','Sociable','Adaptable'],['Gentle','Sociable','Adaptable'],'La santé cardiaque doit être surveillée; choisir un élevage qui effectue les dépistages recommandés.','Heart health requires attention; choose a breeder performing recommended screening.'),
    B('Shih Tzu','Shih Tzu','small','moderate','20–28 cm','4–7,5 kg','Affectueux, assuré, calme à la maison et sociable.','Affectionate, self-assured, calm at home and sociable.','30 à 45 min en sorties courtes; jeux d’intérieur et contacts quotidiens.','30–45 min in short outings, indoor play and daily companionship.','Chien de compagnie au long poil et au museau court, plus robuste qu’il n’en a l’air.','Long-coated, short-muzzled companion sturdier than it appears.',['Affectueux','Joyeux','Adaptable'],['Affectionate','Cheerful','Adaptable'],'Entretien du poil, des yeux et du visage; éviter l’effort par forte chaleur.','Coat, eye and facial care are important; avoid exertion in hot weather.'),
    B('Teckel standard','Standard Dachshund','small','moderate','20–27 cm','7–14,5 kg','Courageux, tenace, amusant et indépendant.','Brave, tenacious, amusing and independent.','45 à 60 min, marche régulière et jeux de flair sans sauts répétés.','45–60 min of steady walking and scent games without repeated jumping.','Chien de chasse bas sur pattes, doté d’un nez puissant et d’une forte personnalité.','Low-set hunting dog with a powerful nose and strong personality.',['Tenace','Vif','Loyal'],['Tenacious','Lively','Loyal'],'Protéger le dos: poids santé, muscles entretenus, escaliers et sauts limités selon l’avis vétérinaire.','Protect the back through healthy weight, fitness and vet-guided limits on stairs and jumping.'),
    B('Boxer','Boxer','large','high','53–63 cm','25–32 kg','Joueur, protecteur, exubérant et très humain.','Playful, protective, exuberant and people-focused.','60 à 90 min, jeux structurés et éducation; éviter la chaleur.','60–90 min of structured play and training; avoid heat.','Molosse athlétique qui reste souvent joueur longtemps et demande une bonne maîtrise des salutations.','Athletic working dog that often stays playful for years and needs polite greeting skills.',['Joueur','Loyal','Courageux'],['Playful','Loyal','Brave'],'Museau court et sensibilité à la chaleur; dépistages cardiaques importants.','Short muzzle and heat sensitivity; cardiac screening is important.'),
    B('Rottweiler','Rottweiler','large','high','56–69 cm','35–60 kg','Calme, puissant, loyal et sûr de lui lorsqu’il est bien socialisé.','Calm, powerful, loyal and confident when well socialized.','60 à 90 min, marche, obéissance et travail mental régulier.','60–90 min of walking, obedience and regular mental work.','Chien de travail imposant, réfléchi et protecteur qui requiert un adulte responsable.','Imposing, thoughtful and protective working dog requiring a responsible adult.',['Loyal','Stable','Travailleur'],['Loyal','Steady','Hard-working'],'Sa force rend l’éducation précoce, la socialisation et la sélection santé indispensables.','Strength makes early training, socialization and health selection essential.'),
    B('Dobermann','Doberman Pinscher','large','very-high','63–72 cm','27–45 kg','Rapide, vigilant, sensible et profondément attaché à sa famille.','Fast, alert, sensitive and deeply bonded to family.','90 à 120 min avec course, obéissance et exercices de réflexion.','90–120 min including running, obedience and problem-solving.','Chien de garde athlétique qui recherche une relation étroite et un cadre cohérent.','Athletic guardian seeking a close bond and consistent guidance.',['Élégant','Loyal','Réactif'],['Elegant','Loyal','Responsive'],'Il tolère mal l’isolement prolongé; le dépistage cardiaque est particulièrement important.','Poor tolerance for prolonged isolation; cardiac screening is especially important.'),
    B('Bouvier bernois','Bernese Mountain Dog','giant','moderate','58–70 cm','32–52 kg','Doux, patient, affectueux et généralement posé.','Gentle, patient, affectionate and usually calm.','60 à 90 min de marche modérée, jeux et vie de famille.','60–90 min of moderate walking, play and family time.','Grand chien suisse de ferme, puissant mais sensible, plus à l’aise au frais.','Large Swiss farm dog, powerful yet sensitive and more comfortable in cool weather.',['Doux','Patient','Dévoué'],['Gentle','Patient','Devoted'],'Espérance de vie relativement courte, chaleur difficile et suivi orthopédique à prévoir.','Relatively short lifespan, poor heat tolerance and orthopedic care considerations.'),
    B('Terre-Neuve','Newfoundland','giant','moderate','63–74 cm','45–68 kg','Très doux, patient, puissant et naturellement à l’aise dans l’eau.','Very gentle, patient, powerful and naturally comfortable in water.','60 à 90 min modérées; nage sécurisée possible et repos au frais.','60–90 moderate minutes; safe swimming may be included, with cool rest.','Géant nageur et secouriste historique, généralement calme mais très encombrant.','Giant swimmer and historic rescue dog, usually calm but space-consuming.',['Patient','Doux','Puissant'],['Patient','Gentle','Powerful'],'Bave, mue, chaleur, budget alimentaire et risques orthopédiques doivent être anticipés.','Drool, shedding, heat, food costs and orthopedic risks must be anticipated.'),
    B('Jack Russell Terrier','Jack Russell Terrier','small','very-high','25–30 cm','5–8 kg','Intrépide, intense, malin et toujours prêt à agir.','Fearless, intense, clever and always ready for action.','60 à 90 min très actives avec flair, apprentissage et jeux contrôlés.','60–90 very active minutes with scent work, training and controlled games.','Petit terrier de travail explosif, souvent plus exigeant qu’un chien beaucoup plus grand.','Explosive small working terrier often more demanding than a much larger dog.',['Courageux','Drôle','Énergique'],['Brave','Funny','Energetic'],'Instinct de chasse marqué, ennui destructeur possible et besoin d’une vraie éducation.','Strong prey drive, potential destructive boredom and a real need for training.'),
    B('Cocker anglais','English Cocker Spaniel','medium','high','38–43 cm','12–15 kg','Joyeux, affectueux, actif et passionné par les odeurs.','Merry, affectionate, active and scent-driven.','60 à 90 min, exploration, rapport et jeux de flair.','60–90 min of exploring, retrieving and scent games.','Épagneul compact et enthousiaste dont les lignées de travail peuvent être très intenses.','Compact, enthusiastic spaniel whose working lines may be especially intense.',['Joyeux','Affectueux','Polyvalent'],['Merry','Affectionate','Versatile'],'Oreilles et pelage demandent un entretien régulier; bien choisir la lignée selon son mode de vie.','Ears and coat need regular care; choose the line carefully for your lifestyle.'),
    B('Dalmatien','Dalmatian','large','very-high','54–62 cm','24–32 kg','Endurant, athlétique, sensible et très reconnaissable.','Enduring, athletic, sensitive and unmistakable.','90 à 120 min avec marche rapide, course progressive et apprentissage.','90–120 min of brisk walking, gradual running and training.','Ancien chien de carrosse fait pour parcourir de longues distances près de sa famille.','Historic carriage dog built to cover long distances beside its family.',['Endurant','Élégant','Joueur'],['Enduring','Elegant','Playful'],'Dépistage auditif important et attention aux besoins urinaires particuliers de la race.','Hearing screening is important, along with awareness of breed-specific urinary concerns.'),
    B('Carlin','Pug','small','moderate','25–33 cm','6,3–8,1 kg','Comique, affectueux, sociable et gourmand.','Comical, affectionate, sociable and food-motivated.','30 à 45 min calmes et fractionnées; aucune activité intense par chaleur.','30–45 calm, split minutes; no intense activity in heat.','Compagnon compact et expressif qui préfère souvent rester près de ses humains.','Compact, expressive companion that usually prefers staying close to people.',['Drôle','Affectueux','Sociable'],['Funny','Affectionate','Sociable'],'Respiration, yeux, plis cutanés et poids exigent une surveillance attentive.','Breathing, eyes, skin folds and weight require careful monitoring.'),
    B('Berger belge malinois','Belgian Malinois','large','very-high','56–66 cm','20–30 kg','Explosif, extrêmement réactif, vigilant et passionné de travail.','Explosive, extremely responsive, vigilant and intensely work-driven.','Au moins 120 min de travail structuré, apprentissage avancé et activité physique.','At least 120 min of structured work, advanced training and physical activity.','Berger de haut niveau utilisé dans les sports et services; rarement adapté à une famille débutante.','High-level herder used in sports and service work; rarely suitable for a novice family.',['Rapide','Brillant','Courageux'],['Fast','Brilliant','Brave'],'Une simple promenade ne suffit pas; l’accompagnement d’un professionnel compétent est fortement conseillé.','A simple walk is not enough; guidance from a skilled professional is strongly recommended.'),
    B('Basenji','Basenji','medium','high','40–43 cm','9–11 kg','Indépendant, propre, curieux et peu porté sur l’aboiement classique.','Independent, clean, curious and not prone to conventional barking.','60 à 90 min avec courses sécurisées et jeux de réflexion.','60–90 min with secure running and problem-solving games.','Ancien chien africain agile qui vocalise autrement et réfléchit avant d’obéir.','Ancient agile African dog that vocalizes differently and thinks before obeying.',['Propre','Élégant','Curieux'],['Clean','Elegant','Curious'],'Rappel difficile, instinct de chasse et besoin d’une clôture réellement sécurisée.','Difficult recall, prey drive and need for truly secure fencing.'),
    B('Azawakh','Azawakh','large','high','60–74 cm','15–25 kg','Fin, rapide, réservé et très fidèle à son cercle proche.','Lean, fast, reserved and deeply loyal to its inner circle.','60 à 90 min avec possibilité de sprint en espace clôturé.','60–90 min with opportunities to sprint in a fenced area.','Lévrier sahélien léger et sensible, adapté à la course et peu protégé du froid.','Light, sensitive Sahelian sighthound built for running and poorly insulated from cold.',['Élégant','Loyal','Rapide'],['Elegant','Loyal','Fast'],'Socialisation fine, vêtements en hiver et prudence avec les petits animaux.','Careful socialization, winter clothing and caution around small animals.'),
    B('Chinook','Chinook','large','high','53–69 cm','23–41 kg','Doux, coopératif, athlétique et plus rare.','Gentle, cooperative, athletic and uncommon.','60 à 90 min, randonnée, traction légère et activités partagées.','60–90 min of hiking, light pulling and shared activities.','Chien de traîneau américain conçu pour combiner puissance, endurance et tempérament sociable.','American sled dog bred to combine strength, endurance and a social temperament.',['Doux','Endurant','Coopératif'],['Gentle','Enduring','Cooperative'],'Race rare: chercher un éleveur responsable et prévoir une attente importante.','Rare breed: seek a responsible breeder and expect a substantial wait.'),
    B('Kai Ken','Kai Ken','medium','high','45–56 cm','11–25 kg','Loyal, vigilant, agile et souvent réservé avec les étrangers.','Loyal, alert, agile and often reserved with strangers.','60 à 90 min, randonnée, flair et sorties sécurisées.','60–90 min of hiking, scent work and secure outings.','Race japonaise primitive au poil bringé, agile sur terrain difficile.','Primitive Japanese brindle breed, agile on difficult terrain.',['Loyal','Agile','Observateur'],['Loyal','Agile','Observant'],'Instinct de chasse et tempérament indépendant; socialisation précoce essentielle.','Prey drive and independent temperament; early socialization is essential.'),
    B('Mudi','Mudi','medium','very-high','38–47 cm','8–13 kg','Vif, polyvalent, vocal et extrêmement rapide à apprendre.','Lively, versatile, vocal and extremely quick to learn.','90 à 120 min avec sport canin, troupeau, flair ou apprentissage complexe.','90–120 min with dog sports, herding, scent work or complex training.','Berger hongrois rare, compact et explosif, à l’aise dans de nombreuses disciplines.','Rare compact, explosive Hungarian herder suited to many disciplines.',['Brillant','Polyvalent','Agile'],['Brilliant','Versatile','Agile'],'Il peut être sensible au bruit et réactif; il a besoin de repos autant que de travail.','May be noise-sensitive and reactive; needs rest as much as work.'),
    B('Pumi','Pumi','medium','very-high','38–47 cm','8–15 kg','Expressif, rapide, intelligent et souvent très vocal.','Expressive, quick, intelligent and often very vocal.','60 à 90 min soutenues avec agilité, apprentissage et jeux de contrôle.','60–90 active minutes with agility, training and impulse-control games.','Berger hongrois bouclé au tempérament de terrier, curieux et remuant.','Curly Hungarian herder with a curious, busy terrier-like temperament.',['Vif','Drôle','Éducable'],['Lively','Funny','Trainable'],'Le niveau sonore et l’énergie demandent une éducation calme et constante.','Voice and energy levels require calm, consistent training.'),
    B('Schipperke','Schipperke','small','high','25–33 cm','4–7 kg','Curieux, vigilant, confiant et très actif pour son format.','Curious, vigilant, confident and highly active for its size.','60 à 90 min, promenades dynamiques, flair et jeux mentaux.','60–90 min of brisk walks, scent work and mental games.','Petit chien belge noir, excellent avertisseur et explorateur infatigable.','Small black Belgian dog, excellent watchdog and tireless explorer.',['Alerte','Courageux','Curieux'],['Alert','Brave','Curious'],'Peut aboyer et fuguer s’il s’ennuie; clôture et rappel travaillés sont importants.','May bark and roam when bored; fencing and recall work matter.'),
    B('Lagotto Romagnolo','Lagotto Romagnolo','medium','high','41–48 cm','11–16 kg','Affectueux, travailleur, attentif et passionné par les odeurs.','Affectionate, hard-working, attentive and scent-driven.','60 à 90 min avec recherche olfactive, promenades et apprentissage.','60–90 min with scent searches, walks and training.','Chien d’eau italien devenu spécialiste de la recherche de truffes.','Italian water dog that became a truffle-searching specialist.',['Excellent nez','Éducable','Affectueux'],['Excellent nose','Trainable','Affectionate'],'Le pelage bouclé demande une tonte régulière; certaines lignées peuvent être sensibles.','Curly coat needs regular clipping; some lines may be sensitive.'),
    B('Chien finnois de Laponie','Finnish Lapphund','medium','high','41–52 cm','15–24 kg','Amical, attentif, robuste et souvent bavard.','Friendly, attentive, sturdy and often vocal.','60 à 90 min, marche, jeux, flair et activités familiales.','60–90 min of walking, games, scent work and family activities.','Berger nordique conçu pour travailler avec les rennes dans un climat froid.','Northern herder developed to work with reindeer in cold climates.',['Amical','Robuste','Réceptif'],['Friendly','Sturdy','Responsive'],'Grosse mue saisonnière, voix présente et besoin de rester au frais en été.','Heavy seasonal shedding, vocal nature and a need to stay cool in summer.'),
    B('Kooikerhondje','Nederlandse Kooikerhondje','medium','high','35–42 cm','9–14 kg','Vif, sensible, intelligent et réservé sans être timide.','Lively, sensitive, intelligent and reserved without being timid.','60 à 90 min avec rapport, flair et apprentissage positif.','60–90 min with retrieving, scent work and positive training.','Petit chien néerlandais utilisé historiquement autour des pièges à canards.','Small Dutch dog historically used around duck decoys.',['Agile','Intelligent','Élégant'],['Agile','Intelligent','Elegant'],'Une socialisation douce et un environnement peu brutal conviennent mieux à sa sensibilité.','Gentle socialization and a low-pressure environment suit this sensitive breed.'),
    B('Xoloitzcuintle moyen','Standard Xoloitzcuintli','medium','moderate','36–45 cm','7–14 kg','Calme à la maison, vigilant, fidèle et singulier.','Calm at home, alert, loyal and distinctive.','45 à 60 min, promenades et jeux modérés.','45–60 min of walks and moderate play.','Ancienne race mexicaine souvent nue, chaude au toucher et réservée avec les étrangers.','Ancient Mexican breed, often hairless, warm to the touch and reserved with strangers.',['Loyal','Calme','Original'],['Loyal','Calm','Distinctive'],'La peau nue exige protection solaire raisonnée et protection contre le froid.','Hairless skin needs sensible sun protection and insulation from cold.'),
    B('Chien d’eau portugais','Portuguese Water Dog','medium','high','43–57 cm','16–27 kg','Énergique, proche de sa famille, intelligent et amateur d’eau.','Energetic, family-oriented, intelligent and water-loving.','60 à 90 min avec nage sécurisée, rapport et apprentissage.','60–90 min with safe swimming, retrieving and training.','Ancien auxiliaire de pêche au poil bouclé ou ondulé, volontaire et robuste.','Former fishing helper with curly or wavy coat; willing and sturdy.',['Athlétique','Éducable','Polyvalent'],['Athletic','Trainable','Versatile'],'Toilettage régulier et besoin d’un vrai engagement quotidien malgré la faible mue.','Regular grooming and genuine daily commitment despite low shedding.'),
    B('Berger de Bohême','Bohemian Shepherd','medium','high','49–55 cm','17–27 kg','Doux, attentif, agile et très attaché à sa famille.','Gentle, attentive, agile and strongly attached to family.','60 à 90 min avec promenades, obéissance et jeux de flair.','60–90 min with walks, obedience and scent games.','Berger tchèque plus léger que le berger allemand, polyvalent et encore peu connu.','Czech herder lighter than a German Shepherd, versatile and still little known.',['Doux','Polyvalent','Réceptif'],['Gentle','Versatile','Responsive'],'Race encore rare hors de son pays; vérifier santé, tempérament et conditions d’élevage.','Still rare outside its homeland; verify health, temperament and breeding conditions.'),
    B('Eurasier','Eurasier','large','moderate','48–60 cm','18–32 kg','Calme, réservé, équilibré et profondément familial.','Calm, reserved, balanced and deeply family-oriented.','Environ 60 min de promenade, exploration et présence avec ses humains.','About 60 min of walking, exploring and time with family.','Spitz européen conçu comme compagnon stable, peu intéressé par le travail répétitif.','European spitz developed as a stable companion, not keen on repetitive work.',['Calme','Loyal','Équilibré'],['Calm','Loyal','Balanced'],'Il supporte mal l’isolement prolongé et ne doit pas être forcé dans des interactions sociales.','Poor tolerance for prolonged isolation and should not be forced into social interactions.'),
    B('Terrier tchèque','Cesky Terrier','small','moderate','25–32 cm','6–10 kg','Posé pour un terrier, curieux, loyal et adaptable.','Calm for a terrier, curious, loyal and adaptable.','45 à 60 min, promenades, jeux de flair et exploration.','45–60 min of walks, scent games and exploring.','Terrier rare aux pattes courtes et au poil soyeux, généralement moins explosif que d’autres terriers.','Rare short-legged, silky-coated terrier, usually less intense than many terriers.',['Adaptable','Loyal','Curieux'],['Adaptable','Loyal','Curious'],'Toilettage par tonte et socialisation nécessaires; l’instinct de chasse reste présent.','Clipping and socialization are needed; prey drive remains present.'),
    B('Otterhound','Otterhound','giant','high','61–69 cm','36–52 kg','Jovial, puissant, indépendant et doté d’un flair remarquable.','Jovial, powerful, independent and gifted with remarkable scent.','90 à 120 min de marche, flair et nage sécurisée.','90–120 min of walking, scent work and safe swimming.','Très rare chien courant britannique, grand, rustique et passionné par l’eau.','Very rare large, rugged British scent hound with a passion for water.',['Jovial','Robuste','Excellent nez'],['Jovial','Sturdy','Excellent nose'],'Voix puissante, rappel difficile, entretien du poil et espace important à prévoir.','Powerful voice, difficult recall, coat care and substantial space needs.'),
    B('Thai Ridgeback','Thai Ridgeback','large','high','51–61 cm','16–34 kg','Athlétique, indépendant, protecteur et réservé.','Athletic, independent, protective and reserved.','60 à 90 min avec course sécurisée et éducation progressive.','60–90 min with secure running and gradual training.','Race primitive thaïlandaise portant une crête dorsale de poils inversés.','Primitive Thai breed with a ridge of reverse-growing hair along the back.',['Agile','Loyal','Vigilant'],['Agile','Loyal','Alert'],'Peu conseillé aux débutants: socialisation, gestion de l’instinct de chasse et clôture sont essentielles.','Not ideal for beginners: socialization, prey-drive management and fencing are essential.'),
    B('Lévrier afghan','Afghan Hound','large','high','63–74 cm','23–27 kg','Digne, indépendant, rapide et spectaculaire.','Dignified, independent, fast and striking.','60 à 90 min avec occasion de courir librement dans un espace très sécurisé.','60–90 min with chances to run freely in a very secure area.','Lévrier ancien au long pelage, réservé mais parfois clown avec ses proches.','Ancient long-coated sighthound, reserved yet sometimes clownish with family.',['Élégant','Rapide','Digne'],['Elegant','Fast','Dignified'],'Toilettage exigeant, rappel incertain et forte poursuite des petits animaux.','Demanding grooming, uncertain recall and strong pursuit of small animals.'),
    B('Akita','Akita','large','high','61–71 cm','32–59 kg','Digne, puissant, calme et très loyal à son foyer.','Dignified, powerful, calm and deeply loyal to its household.','60 à 90 min de marche structurée et stimulation calme.','60–90 min of structured walking and calm mental stimulation.','Grand spitz japonais réservé, protecteur et souvent peu tolérant envers les chiens du même sexe.','Large reserved, protective Japanese spitz, often intolerant of same-sex dogs.',['Loyal','Calme','Courageux'],['Loyal','Calm','Brave'],'Demande une personne expérimentée, une socialisation réfléchie et une gestion responsable des rencontres.','Needs an experienced owner, thoughtful socialization and responsible encounter management.')
  ];

  const els = {
    language: document.getElementById('language'), search: document.getElementById('search'), size: document.getElementById('sizeFilter'), activity: document.getElementById('activityFilter'), count: document.getElementById('count'), grid: document.getElementById('breedGrid'), modal: document.getElementById('breedModal'), close: document.getElementById('modalClose')
  };
  let lang = localStorage.getItem('dicopetsLanguage') === 'en' ? 'en' : 'fr';
  let currentBreed = null;
  const activityText = {fr:{moderate:'Modérée',high:'Élevée','very-high':'Très élevée'},en:{moderate:'Moderate',high:'High','very-high':'Very high'}};
  const sizeText = {fr:{small:'Petit chien',medium:'Chien moyen',large:'Grand chien',giant:'Chien géant'},en:{small:'Small dog',medium:'Medium dog',large:'Large dog',giant:'Giant dog'}};
  const normalize = value => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const advancedBreeds = new Set(['Akita','Shiba Inu','Basenji','Thai Ridgeback','Border Collie','Berger belge malinois','Husky sibérien','Jack Russell Terrier','Rottweiler','Dobermann','Otterhound','Lévrier afghan']);
  const intermediateBreeds = new Set(['Berger allemand','Berger australien','Samoyède','Beagle','Schnauzer nain','Welsh Corgi Cardigan','Welsh Corgi Pembroke','Lagotto Romagnolo','Chien d’eau portugais','Mudi','Pumi']);

  function idealOwner(b){
    const suffix=lang==='fr'?'Fr':'En',attached=/attach|proche|famill|humain|people|family|compagn/i.test(`${b.traitsFr} ${b.characterFr} ${b.knowFr}`);
    let homeFr,homeEn;
    if(b.size==='small'){
      homeFr=b.activity==='moderate'?'Appartement ou maison; un espace extérieur privé n’est pas obligatoire.':'Appartement possible avec plusieurs sorties; maison sécurisée appréciée.';
      homeEn=b.activity==='moderate'?'Apartment or house; a private yard is not essential.':'Apartment possible with several outings; a secure house is appreciated.';
    }else if(b.size==='medium'){
      homeFr=b.activity==='moderate'?'Appartement spacieux ou maison, avec sorties quotidiennes régulières.':'Maison idéale; appartement possible pour une personne très active et disponible.';
      homeEn=b.activity==='moderate'?'Spacious apartment or house, with regular daily outings.':'House preferred; an apartment can work for a very active and available person.';
    }else if(b.size==='giant'){
      homeFr='Logement spacieux, accès facile à l’extérieur et déplacements sans escaliers répétés.';homeEn='Spacious home, easy outdoor access and no need for repeated stairs.';
    }else{
      homeFr=b.activity==='moderate'?'Maison ou grand appartement, avec espace de repos et sorties régulières.':'Maison avec espace sécurisé recommandée; le jardin ne remplace jamais les sorties.';
      homeEn=b.activity==='moderate'?'House or large apartment, with resting space and regular outings.':'House with secure space recommended; a yard never replaces proper outings.';
    }
    let experienceFr='Convient à une personne débutante bien informée, patiente et prête à apprendre.',experienceEn='Can suit a well-informed beginner who is patient and willing to learn.';
    if(intermediateBreeds.has(b.fr)){experienceFr='Une première expérience canine est préférable, avec une éducation régulière et positive.';experienceEn='Some previous dog experience is preferable, with regular positive training.'}
    if(advancedBreeds.has(b.fr)){experienceFr='Maître expérimenté recommandé, capable d’offrir structure, socialisation et gestion cohérente.';experienceEn='Experienced owner recommended, able to provide structure, socialization and consistent management.'}
    const presenceFr=attached?'Présence fréquente et vraie vie familiale; éviter les longues absences quotidiennes.':b.activity==='very-high'?'Plusieurs périodes disponibles chaque jour pour sorties, travail mental et récupération.':'Du temps chaque jour pour les sorties et les interactions, avec un apprentissage progressif de la solitude.';
    const presenceEn=attached?'Frequent company and genuine family life; avoid long daily absences.':b.activity==='very-high'?'Several available periods each day for outings, mental work and recovery.':'Daily time for outings and interaction, with gradual training for time alone.';
    const lifestyleFr=b.activity==='very-high'?'Très actif et structuré : sport, apprentissages et activités mentales presque tous les jours.':b.activity==='high'?'Actif et disponible : promenades variées, jeux de flair et apprentissages réguliers.':'Calme mais présent : promenades régulières, jeux doux et routine stable.';
    const lifestyleEn=b.activity==='very-high'?'Highly active and structured: sport, training and mental activities almost every day.':b.activity==='high'?'Active and available: varied walks, scent games and regular training.':'Calm but present: regular walks, gentle games and a stable routine.';
    return {home:lang==='fr'?homeFr:homeEn,time:b[`daily${suffix}`],experience:lang==='fr'?experienceFr:experienceEn,presence:lang==='fr'?presenceFr:presenceEn,lifestyle:lang==='fr'?lifestyleFr:lifestyleEn};
  }

  function applyLanguage(){
    lang = els.language.value;
    localStorage.setItem('dicopetsLanguage',lang);
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-fr][data-en]').forEach(el => el.textContent = el.dataset[lang]);
    document.querySelectorAll('[data-placeholder-fr]').forEach(el => el.placeholder = el.dataset[`placeholder${lang === 'fr' ? 'Fr' : 'En'}`]);
    render();
    if(currentBreed) fillModal(currentBreed);
  }

  function filtered(){
    const query = normalize(els.search.value);
    return breeds.filter(b => {
      const text = normalize([b.fr,b.en,b.traitsFr,b.traitsEn,b.characterFr,b.characterEn,b.qualitiesFr.join(' '),b.qualitiesEn.join(' ')].join(' '));
      return (!query || text.includes(query)) && (els.size.value === 'all' || b.size === els.size.value) && (els.activity.value === 'all' || b.activity === els.activity.value);
    });
  }

  function render(){
    const list = filtered();
    els.count.textContent = lang === 'fr' ? `${list.length} race${list.length > 1 ? 's' : ''}` : `${list.length} breed${list.length !== 1 ? 's' : ''}`;
    if(!list.length){ els.grid.innerHTML = `<p class="empty">${lang === 'fr' ? 'Aucune race ne correspond à ces filtres.' : 'No breed matches these filters.'}</p>`; return; }
    els.grid.replaceChildren(...list.map(b => {
      const card = document.createElement('article'); card.className = 'card';
      const top = document.createElement('div'); top.className = 'card-top';
      const title = document.createElement('h3'); title.textContent = b[lang];
      const badge = document.createElement('span'); badge.className = 'badge'; badge.textContent = sizeText[lang][b.size]; top.append(title,badge);
      const traits = document.createElement('p'); traits.className = 'traits'; traits.textContent = b[`traits${lang === 'fr' ? 'Fr' : 'En'}`];
      const facts = document.createElement('div'); facts.className = 'facts'; facts.innerHTML = `<span class="fact"><strong>${lang === 'fr' ? 'Taille' : 'Height'}</strong>${b.height}</span><span class="fact"><strong>${lang === 'fr' ? 'Activité' : 'Activity'}</strong>${activityText[lang][b.activity]}</span>`;
      const button = document.createElement('button'); button.className = 'open'; button.type = 'button'; button.textContent = lang === 'fr' ? 'Voir la fiche complète →' : 'Open full profile →'; button.addEventListener('click',()=>openModal(b));
      card.append(top,traits,facts,button); return card;
    }));
  }

  function fillModal(b){
    const suffix = lang === 'fr' ? 'Fr' : 'En';
    document.getElementById('modalSize').textContent = sizeText[lang][b.size];
    document.getElementById('modalTitle').textContent = b[lang];
    document.getElementById('modalSummary').textContent = b[`traits${suffix}`];
    document.getElementById('modalHeight').textContent = b.height;
    document.getElementById('modalWeight').textContent = b.weight;
    document.getElementById('modalActivity').textContent = activityText[lang][b.activity];
    document.getElementById('modalDaily').textContent = b[`daily${suffix}`];
    document.getElementById('modalCharacteristics').textContent = b[`character${suffix}`];
    document.getElementById('modalKnow').textContent = b[`know${suffix}`];
    const owner=idealOwner(b);
    document.getElementById('modalIdealHome').textContent=owner.home;
    document.getElementById('modalIdealTime').textContent=owner.time;
    document.getElementById('modalIdealExperience').textContent=owner.experience;
    document.getElementById('modalIdealPresence').textContent=owner.presence;
    document.getElementById('modalIdealLifestyle').textContent=owner.lifestyle;
    const qualities = b[`qualities${suffix}`]; document.getElementById('modalQualities').replaceChildren(...qualities.map(q => {const span=document.createElement('span');span.className='quality';span.textContent=q;return span;}));
    const term = lang === 'fr' ? `${b.fr} race de chien caractéristiques` : `${b.en} dog breed characteristics`;
    document.getElementById('googleLink').href = `https://www.google.com/search?q=${encodeURIComponent(term)}`;
  }
  function openModal(b){currentBreed=b;fillModal(b);els.modal.classList.add('open');document.body.classList.add('modal-open');els.close.focus();}
  function closeModal(){els.modal.classList.remove('open');document.body.classList.remove('modal-open');currentBreed=null;}
  els.language.value=lang; els.language.addEventListener('change',applyLanguage); els.search.addEventListener('input',render); els.size.addEventListener('change',render); els.activity.addEventListener('change',render); els.close.addEventListener('click',closeModal); els.modal.addEventListener('click',e=>{if(e.target===els.modal)closeModal();}); document.addEventListener('keydown',e=>{if(e.key==='Escape'&&currentBreed)closeModal();}); applyLanguage(); const requested=new URLSearchParams(location.search).get('breed');if(requested){const clean=value=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const match=breeds.find(b=>clean(b.fr)===clean(requested)||clean(b.en)===clean(requested));if(match)setTimeout(()=>openModal(match),250)}
})();

(() => {
  const heads=[...document.querySelectorAll('main .section-head')],tools=document.querySelector('.tool-grid'),journal=document.querySelector('.dog-journal'),controls=document.querySelector('.controls'),breedHead=heads[1],grid=document.getElementById('breedGrid');
  const health=document.querySelector('a[href="outils-chien.html#soins"]');if(health)health.href='soins-chien.html';
  const toolRoutes={ideal:'ideal',education:'education',budget:'budget',quiz:'quiz',noms:'noms'};Object.entries(toolRoutes).forEach(([hash,route])=>{const link=document.querySelector(`a[href="outils-chien.html#${hash}"]`);if(link)link.href=`outils-chien.html?outil=${route}`});
  const style=document.createElement('style');style.textContent='.breed-door{display:grid;grid-template-columns:100px 1fr auto;gap:22px;align-items:center;margin:0 0 58px;padding:25px;border:1px solid #d6dfd5;border-radius:20px;background:linear-gradient(125deg,#fffdf8,#e8f1e9);box-shadow:0 12px 30px #173b3014}.breed-door-icon{display:grid;place-items:center;width:90px;height:90px;border-radius:50%;background:#173b30;font-size:44px}.breed-door h2{margin:0 0 7px;font-size:34px}.breed-door p{margin:0;color:#60746a}.breed-door a,.race-return{display:inline-flex;padding:13px 18px;border-radius:999px;background:#b88a44;color:#fff;text-decoration:none;font-weight:900}.race-return{margin:0 0 25px;background:#173b30}@media(max-width:650px){.breed-door{grid-template-columns:70px 1fr}.breed-door-icon{width:66px;height:66px;font-size:32px}.breed-door a{grid-column:1/-1;justify-content:center}}';document.head.appendChild(style);
  const raceMode=new URLSearchParams(location.search).get('section')==='races';
  if(raceMode){document.querySelector('.hero').style.display='none';if(heads[0])heads[0].style.display='none';if(tools)tools.style.display='none';if(journal)journal.style.display='none';const back=document.createElement('a');back.className='race-return';back.href='dicochien.html';back.textContent='← Retour à DicoChien';breedHead?.before(back);document.title='Races de chiens · DicoPets';}
  else{if(controls)controls.style.display='none';if(breedHead)breedHead.style.display='none';if(grid)grid.style.display='none';const door=document.createElement('section');door.className='breed-door';door.innerHTML='<div class="breed-door-icon">🐶</div><div><h2>Races de chiens</h2><p>Découvre les tailles, besoins, qualités et particularités de nombreuses races, dont le Welsh Corgi Pembroke.</p></div><a href="dicochien.html?section=races">Ouvrir les races →</a>';journal?.before(door);}
  const readable=document.createElement('style');readable.textContent='.language,.language option{background:#fff!important;color:#173b30!important}.topbar a[href^="credits"]{padding:11px 17px!important;font-size:14px!important;background:#fff!important;color:#173b30!important;border:2px solid #e7c47f!important;box-shadow:0 6px 14px #0d291f28!important;transition:transform .2s ease,background .2s ease!important}.topbar a[href^="credits"]:hover{background:#f3dfb8!important;transform:translateY(-2px)!important}html[data-theme="dark"] .topbar a[href^="credits"]{background:#294b3d!important;color:#f4f8f4!important;border-color:#e7c47f!important;box-shadow:none!important}html[data-theme="dark"] .topbar a[href^="credits"]:hover{background:#365e4d!important;color:#fff!important}html[data-theme="dark"] .language,html[data-theme="dark"] .language option{background:#17251f!important;color:#f4f8f4!important;border-color:#5d806f!important}html[data-theme="dark"] .controls{background:#13231df2!important;border-color:#365047!important}html[data-theme="dark"] .search,html[data-theme="dark"] .select{background:#111f19!important;color:#edf4ef!important;border-color:#5d806f!important}html[data-theme="dark"] .count,html[data-theme="dark"] .section-head p,html[data-theme="dark"] .traits,html[data-theme="dark"] .tool-card p,html[data-theme="dark"] .source-note{color:#c5d4cc!important}html[data-theme="dark"] .tool-card,html[data-theme="dark"] .card,html[data-theme="dark"] .breed-door{background:#17251f!important;color:#edf4ef!important;border-color:#365047!important;box-shadow:none!important}html[data-theme="dark"] .tool-card h3,html[data-theme="dark"] .tool-card strong,html[data-theme="dark"] .card h3,html[data-theme="dark"] .section-head h2{color:#f4f8f4!important}html[data-theme="dark"] .fact{background:#213a30!important;color:#edf4ef!important}html[data-theme="dark"] .fact strong{color:#e8c985!important}html[data-theme="dark"] .badge{background:#294b3d!important;color:#f4f8f4!important;border:1px solid #5d806f!important}html[data-theme="dark"] .sheet,html[data-theme="dark"] .account-box{background:#17251f!important;color:#edf4ef!important;border-color:#365047!important}html[data-theme="dark"] .sheet h2,html[data-theme="dark"] .summary,html[data-theme="dark"] .detail,html[data-theme="dark"] .detail span,html[data-theme="dark"] .detail-grid{color:#edf4ef!important}html[data-theme="dark"] .detail{background:#213a30!important;border-color:#456158!important}html[data-theme="dark"] .detail strong{color:#e8c985!important}html[data-theme="dark"] .quality{background:#294b3d!important;color:#f4f8f4!important;border:1px solid #5d806f!important}html[data-theme="dark"] .close,html[data-theme="dark"] .password-eye,html[data-theme="dark"] .account-close{background:#294b3d!important;color:#f4f8f4!important;border-color:#5d806f!important}';document.head.appendChild(readable);
  const cards=[['World breed map','Discover where breeds come from using paw-shaped markers.','Open the map →'],['My ideal dog','A questionnaire matching your lifestyle with breed needs.','Take the test →'],['Care and health','Prevention, food, grooming and important warning signs.','Explore →'],['Training and behaviour','Understand behaviour and teach with kindness.','Explore →'],['Annual budget','Estimate expenses according to breed and size.','Calculate →'],['Quiz and badges','Test your knowledge and unlock a canine badge.','Start →'],['Dog names','Generate names by theme and first letter.','Find a name →'],['Private calendar','Appointments, vaccines and reminders connected to your journal.','Open →']];
  function translateExtras(){const en=document.getElementById('language').value==='en';document.querySelectorAll('.tool-card').forEach((card,i)=>{if(!card.dataset.frTitle){card.dataset.frTitle=card.querySelector('h3').textContent;card.dataset.frText=card.querySelector('p').textContent;card.dataset.frAction=card.querySelector('strong').textContent}const t=cards[i];card.querySelector('h3').textContent=en?t[0]:card.dataset.frTitle;card.querySelector('p').textContent=en?t[1]:card.dataset.frText;card.querySelector('strong').textContent=en?t[2]:card.dataset.frAction});const door=document.querySelector('.breed-door');if(door){door.querySelector('h2').textContent=en?'Dog breeds':'Races de chiens';door.querySelector('p').textContent=en?'Explore the size, needs, strengths and special traits of many breeds, including both Welsh Corgis.':'Découvre les tailles, besoins, qualités et particularités de nombreuses races, dont les deux Corgis gallois.';door.querySelector('a').textContent=en?'Open dog breeds →':'Ouvrir les races →'}const back=document.querySelector('.race-return');if(back)back.textContent=en?'← Back to DicoChien':'← Retour à DicoChien'}
  document.getElementById('language').addEventListener('change',translateExtras);translateExtras();
})();
