(()=>{'use strict';const $=id=>document.getElementById(id),db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP'),ALL_REMINDERS=[0,15,30,45,60,120,1440];let user=null,entries=[],events=[];const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const reminderLabel=minutes=>minutes===0?'à l’heure exacte':minutes<60?`${minutes} min avant`:minutes===60?'1 h avant':minutes===1440?'1 jour avant':`${minutes/60} h avant`;
function render(){$('entries').innerHTML=entries.slice().reverse().map(x=>`<article class="entry"><button class="delete" data-entry="${x.id}">×</button><h3>${esc(x.title)}</h3><small>${new Date(x.created).toLocaleDateString('fr-CA')}</small><p>${esc(x.text)}</p></article>`).join('')||'<p>Aucune page enregistrée.</p>';$('events').innerHTML=events.slice().sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)).map(x=>`<article class="entry"><button class="delete" data-event="${x.id}">×</button><h3>${esc(x.title)}</h3><small>${esc(x.date)} · ${esc(x.time)} · rappel ${reminderLabel(Number(x.reminderMinutes??60))}</small></article>`).join('')||'<p>Aucun événement.</p>';document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>{entries=entries.filter(x=>x.id!==b.dataset.entry);save()});document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{events=events.filter(x=>x.id!==b.dataset.event);clearReminders(b.dataset.event);save()})}
async function save(){if(!user)return;await db.auth.updateUser({data:{cat_journal_entries:entries.slice(-50),cat_calendar_events:events.slice(-50)}});render()}
function open(u){user=u;entries=u.user_metadata?.cat_journal_entries||[];events=u.user_metadata?.cat_calendar_events||[];$('loginBox').classList.add('hidden');$('privateArea').classList.remove('hidden');$('memberName').textContent=u.user_metadata?.pseudo||u.email;render();events.forEach(event=>schedule(event,{remote:false}))}function close(){$('loginBox').classList.remove('hidden');$('privateArea').classList.add('hidden');user=null}
$('login').onclick=async()=>{const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('message').textContent=error?error.message:'';if(data.user)open(data.user)};$('logout').onclick=async()=>{await db.auth.signOut();close()};
$('saveEntry').onclick=()=>{const title=$('entryTitle').value.trim(),text=$('entryText').value.trim();if(!title||!text)return;entries.push({id:crypto.randomUUID(),title,text,created:new Date().toISOString()});$('entryTitle').value=$('entryText').value='';save()};
function clearReminders(id){ALL_REMINDERS.forEach(minutes=>window.DicoPetsNotifications?.remove(`cat-${id}-${minutes}`))}
async function schedule(x,{remote=true}={}){if(!x.date||!x.time)return[];const at=new Date(`${x.date}T${x.time}:00`),minutes=ALL_REMINDERS.includes(Number(x.reminderMinutes))?Number(x.reminderMinutes):60,english=x.reminderLanguage==='en',clock=at.toLocaleTimeString(english?'en-US':'fr-CA',{hour:'2-digit',minute:'2-digit'}),before=english?(minutes===60?'1 hour before':minutes<60?`${minutes} minutes before`:minutes===1440?'1 day before':`${minutes/60} hours before`):reminderLabel(minutes),send=(offset,title,body)=>window.DicoPetsNotifications?.schedule({id:`cat-${x.id}-${offset}`,title,body,when:at.getTime()-offset*60000,url:'journal-chat.html'},{remote}),results=[];if(minutes>0)results.push(await send(minutes,english?`DicoChat reminder · ${before}`:`Rappel DicoChat · ${before}`,english?`${x.title} is scheduled for ${clock}.`:`${x.title} est prévu à ${clock}.`));results.push(await send(0,english?'DicoChat appointment':'Rendez-vous DicoChat',english?`${x.title} is scheduled now, at ${clock}.`:`${x.title} est prévu maintenant, à ${clock}.`));return results}
$('saveEvent').onclick=async()=>{const title=$('eventTitle').value.trim(),date=$('eventDate').value,time=$('eventTime').value,reminderMinutes=Number($('eventReminder').value),reminderLanguage=$('eventReminderLanguage').value==='en'?'en':'fr';if(!title||!date||!time){$('notificationStatus').textContent='Ajoute une date, une heure et un titre pour créer un rappel exact.';return}const x={id:crypto.randomUUID(),title,date,time,reminderMinutes:ALL_REMINDERS.includes(reminderMinutes)?reminderMinutes:60,reminderLanguage};events.push(x);const results=await schedule(x);$('eventTitle').value=$('eventDate').value=$('eventTime').value='';$('eventReminder').value='60';$('eventReminderLanguage').value=document.documentElement.lang.toLowerCase().startsWith('en')?'en':'fr';await save();const failed=results.some(result=>result&&!result.saved&&result.reason!=='login');$('notificationStatus').textContent=failed?'Événement enregistré, mais le rappel distant n’a pas été enregistré. Active les notifications et vérifie Supabase.':'Événement ajouté : le rappel est programmé à l’heure choisie.'};$('eventReminderLanguage').value=document.documentElement.lang.toLowerCase().startsWith('en')?'en':'fr';$('enableNotifications').onclick=async()=>{const result=await window.DicoPetsNotifications.enable();$('notificationStatus').textContent=result.message};
db.auth.getSession().then(({data})=>data.session?.user?open(data.session.user):close());db.auth.onAuthStateChange((_e,s)=>s?.user?open(s.user):close());
})();
