/* Sélecteur de langue commun aux pages dédiées. */
(()=>{
  const en=localStorage.getItem('dicochevalLanguage')==='en';
  const top=document.querySelector('.top');if(!top)return;
  const select=document.createElement('select');select.className='page-language';select.innerHTML='<option value="fr">Français</option><option value="en">English</option>';select.value=en?'en':'fr';top.append(select);select.onchange=()=>{localStorage.setItem('dicochevalLanguage',select.value);localStorage.setItem('dicochevalLocale',select.value==='en'?'en-US':'fr-FR');location.reload()};
  document.head.insertAdjacentHTML('beforeend','<style>.page-language{margin-left:auto;background:#fff;color:#193229;border:0;border-radius:16px;padding:8px 10px;font-weight:bold}.top>a{margin-left:12px}</style>');
  if(!en)return;document.documentElement.lang='en-US';
  const file=location.pathname.split('/').pop();
  const replace=(pairs)=>{const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode);a.forEach(n=>{if(n.parentElement.closest('script,style,option'))return;const s=n.nodeValue.trim();if(pairs[s])n.nodeValue=n.nodeValue.replace(s,pairs[s])})};
  const common={'← Retour à l’accueil':'← Back to home','DicoCheval':'DicoCheval'};
  if(file==='races.html')replace({...common,'Guide des races':'Breed guide','Races équines':'Horse breeds','Découvre les chevaux et les poneys, puis ouvre une fiche complète avec leurs caractéristiques. Les tailles et poids restent indicatifs : chaque animal est unique.':'Explore horses and ponies, then open a full profile with their characteristics. Heights and weights are indicative: every animal is unique.','Rechercher une race…':'Search a breed…','Toutes':'All','Chevaux':'Horses','Poneys':'Ponies','FICHE RACE':'BREED PROFILE','Taille':'Height','Poids':'Weight','Robes':'Coat colors','Qualités':'Qualities','Disciplines':'Disciplines','À savoir':'Good to know','Rechercher des images':'Search for images'});
  if(file==='cheval-ideal.html')replace({...common,'Questionnaire indicatif':'Guidance questionnaire','Mon cheval idéal':'My ideal horse','Cette fiche donne des pistes selon ton expérience, tes envies et ton gabarit. Elle ne remplace jamais l’avis d’un moniteur ou d’un professionnel avant une acquisition.':'This tool gives ideas based on your experience, goals and build. It never replaces advice from an instructor or professional before buying a horse.','Ton expérience':'Your experience','Ce que tu préfères':'What you prefer','Type souhaité':'Preferred type','Ton poids':'Your weight','Ta taille':'Your height','Trouver ma race':'Find my breeds','Choisir…':'Choose…','Je débute':'I am a beginner','Je monte régulièrement':'I ride regularly','Je veux un cheval sportif':'I want a sporty horse','Calme et proche de l’humain':'Calm and people-oriented','Randonnée et extérieur':'Trail riding and outdoors','Saut et polyvalence':'Jumping and versatility','Poney':'Pony','Cheval moyen':'Medium horse','Grand cheval':'Large horse','kilogrammes':'kilograms','livres':'pounds','centimètres':'centimetres','pieds (ex. 5.4)':'feet (e.g. 5.4)'});
  if(file==='equipement-cheval.html')replace({...common,'Bien choisir et ajuster':'Choosing and fitting equipment','Équipement du cheval':'Horse equipment','Deux univers, deux selles : l’équipement doit toujours être adapté au cheval, à sa discipline et ajusté par une personne compétente.':'Two styles, two saddles: equipment must always suit the horse, its discipline, and be fitted by a knowledgeable person.','Équitation classique':'English riding','Équitation western':'Western riding'});
  if(file==='equipement-cavalier.html')replace({...common,'Confort et sécurité':'Comfort and safety','Équipement de la cavalière':'Rider equipment','Le casque homologué est indispensable. Le reste se choisit selon la discipline, la météo et le confort de la personne qui monte.':'A certified helmet is essential. The rest depends on the discipline, weather and rider comfort.','Tenue classique':'English riding outfit','Tenue western':'Western riding outfit'});
})();