/* Thème DicoPets : automatique par heure locale, appareil ou choix manuel. */
(()=>{'use strict';
  const KEY='dicopetsThemePreference',valid=new Set(['auto','system','light','dark']);
  const media=matchMedia('(prefers-color-scheme: dark)');
  let preference=valid.has(localStorage.getItem(KEY))?localStorage.getItem(KEY):'auto';
  const isNight=()=>{const hour=new Date().getHours();return hour>=18||hour<8};
  const resolved=()=>preference==='dark'||(preference==='system'&&media.matches)||(preference==='auto'&&(isNight()||media.matches))?'dark':'light';
  function apply(){const theme=resolved();document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#0d1814':'#173b30');document.querySelectorAll('#memberThemePreference').forEach(x=>x.value=preference);window.dispatchEvent(new CustomEvent('dicopets-theme-change',{detail:{preference,theme}}))}
  function set(value,saveRemote=true){preference=valid.has(value)?value:'auto';localStorage.setItem(KEY,preference);apply();if(saveRemote&&window.supabase){try{const db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');db.auth.getUser().then(({data})=>data.user&&db.auth.updateUser({data:{theme_preference:preference}}))}catch(_){}}}
  apply();if(media.addEventListener)media.addEventListener('change',apply);else media.addListener?.(apply);setInterval(()=>{if(preference==='auto')apply()},60000);
  const style=document.createElement('style');style.textContent=`
  html[data-theme="dark"] body{background:#0e1814!important;color:#e6eee9!important}
  html[data-theme="dark"]{--cream:#0e1814!important;--paper:#17251f!important;--ink:#e6eee9!important;--muted:#a9bbb1!important;--line:#365047!important;--soft:#21342b!important;--white:#17251f!important;--sky:#162822!important;--rose:#2a2027!important}
  html[data-theme="dark"] :is(.card,.tool,.tool-card,.panel,.detail,.fact,.recommendation,.credit,.promise-grid article,.modal-box,.account-box,.member-box,.sheet,.calendar-panel,.book,.entry-pages,.library,.question,.term,.job,.disc,.world-card,.news-card,.event-card,.member-notification,.signup-reminder-card,.entry,.notice,.guide-card,.mission,.auth-box,.calendar-entry,details,.official-comments,.comment){background-color:#17251f!important;color:#e6eee9!important;border-color:#365047!important}
  html[data-theme="dark"] :is(.card,.tool,.tool-card,.panel,.detail,.fact,.recommendation,.credit,.promise-grid article,.modal-box,.account-box,.member-box,.sheet,.calendar-panel,.book,.entry-pages,.library,.question,.term,.job,.disc,.world-card,.news-card,.event-card,.member-notification,.signup-reminder-card,.entry,.notice,.guide-card,.mission,.auth-box,.calendar-entry,details,.official-comments,.comment) :is(h1,h2,h3,h4,h5,p,small,span,label,li,summary,strong,b){color:#d9e7df!important}
  html[data-theme="dark"] :is(input,textarea,select,.search){background:#111f19!important;color:#edf4ef!important;border-color:#496158!important}
  html[data-theme="dark"] :is(.controls,.nav){background:#13231ddd!important;border-color:#365047!important}
  html[data-theme="dark"] :is(.section,.tools,.breeds,.main,.promise,.news,.news-section){background-color:#0e1814!important;color:#e6eee9!important}
  html[data-theme="dark"] :is(h1,h2,h3,h4,strong,b){color:#f1f6f3}
  html[data-theme="dark"] .book{background:#17251f!important}
  html[data-theme="dark"] .member-theme{border-color:#365047!important}
  html[data-theme="dark"] :is(.result,.names span,.answers button,.ideal-card .why,.budget-lines span,.badge){background:#1b3027!important;color:#e6eee9!important;border-color:#456158!important}
  html[data-theme="dark"] :is(.result,.recommendations,.ideal-card,.budget-lines) :is(p,span,small,label){color:#c5d4cc!important}
  html[data-theme="dark"] .budget-total{color:#e8c985!important}
  html[data-theme="dark"] .ideal-master{background:linear-gradient(135deg,#10271f,#244b3d)!important;color:#fff!important}
  html[data-theme="dark"] .ideal-master :is(span,p){color:#edf4ef!important}
  html[data-theme="dark"] :is(.top,.topbar,.hero,.dog-journal,header) :is(h1,h2,h3,h4,h5,p,small,span,label,strong,b,a){color:#eef5f0!important}
  html[data-theme="dark"] :is(.top,.topbar,.hero,.dog-journal,header) .eyebrow{color:#e8c985!important}
  html[data-theme="dark"] .hero .credits-hero-button{background:#fffdf8!important;color:#173b30!important}
  html[data-theme="dark"] a:not(.button):not(.btn):not(.google):not(.journal-button){color:#e8c985}
  .member-theme{border-top:1px solid #dde7dd;margin-top:20px;padding-top:16px}.member-theme label{display:block;font-weight:800;margin-bottom:6px}.member-theme select{width:100%;padding:11px;border:1px solid #cbd8ce;border-radius:8px;background:#fff;color:#234238;font:inherit}.member-theme p{font-size:12px;color:#60746a}
  `;document.head.appendChild(style);
  function translateControl(){const section=document.querySelector('.member-theme');if(!section)return;const en=document.documentElement.lang.toLowerCase().startsWith('en'),texts=en?['Site appearance','Display mode','Automatic — local time and device','Follow my device only','Always light','Always dark','In automatic mode, the site is dark from 6 p.m. to 8 a.m. local time and also respects your device’s dark mode.']:['Apparence du site','Mode d’affichage','Automatique — heure locale et appareil','Suivre uniquement mon appareil','Toujours clair','Toujours sombre','En automatique, le site passe en sombre entre 18 h et 8 h, selon ton fuseau horaire, et respecte aussi le mode sombre de ton appareil.'];section.querySelector('h3').textContent=texts[0];section.querySelector('label').textContent=texts[1];[...section.querySelectorAll('option')].forEach((x,i)=>x.textContent=texts[i+2]);section.querySelector('p').textContent=texts[6]}
  function addMemberControl(){const box=document.querySelector('#memberModal .member-box');if(!box||box.querySelector('.member-theme'))return;const section=document.createElement('section');section.className='member-theme';section.innerHTML='<h3>Apparence du site</h3><label for="memberThemePreference">Mode d’affichage</label><select id="memberThemePreference"><option value="auto">Automatique — heure locale et appareil</option><option value="system">Suivre uniquement mon appareil</option><option value="light">Toujours clair</option><option value="dark">Toujours sombre</option></select><p></p>';const actions=box.querySelector('.member-actions');box.insertBefore(section,actions);section.querySelector('select').value=preference;section.querySelector('select').addEventListener('change',e=>set(e.target.value));translateControl()}
  async function loadAccountPreference(){if(!window.supabase)return;try{const db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');const {data}=await db.auth.getUser(),remote=data.user?.user_metadata?.theme_preference;if(valid.has(remote)){preference=remote;localStorage.setItem(KEY,remote);apply()}db.auth.onAuthStateChange((_e,session)=>{const value=session?.user?.user_metadata?.theme_preference;if(valid.has(value)){preference=value;localStorage.setItem(KEY,value);apply()}})}catch(_){}}
  document.addEventListener('DOMContentLoaded',()=>{addMemberControl();new MutationObserver(translateControl).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});window.addEventListener('dicopets-language-change',translateControl);loadAccountPreference()});
  window.DicoPetsTheme={set,getPreference:()=>preference,getTheme:resolved};
})();
